@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jan 26 16:28:53 -0500 2026
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_dut_hostlike_behav -key {Behavioral:sim_1:Functional:tb_dut_hostlike} -tclbatch tb_dut_hostlike.tcl -view C:/Users/kmejbaulislam/Documents/Research/Dipal_project/d_pin_skew/d_pin_skew.srcs/sim_1/imports/cw305_aes256_dpin_skew/aes_tb_behav1.wcfg -log simulate.log"
call xsim  tb_dut_hostlike_behav -key {Behavioral:sim_1:Functional:tb_dut_hostlike} -tclbatch tb_dut_hostlike.tcl -view C:/Users/kmejbaulislam/Documents/Research/Dipal_project/d_pin_skew/d_pin_skew.srcs/sim_1/imports/cw305_aes256_dpin_skew/aes_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
