// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_lenet_Pipeline_VITIS_LOOP_1079_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dense3_output_address0,
        dense3_output_ce0,
        dense3_output_q0,
        dense3_output_address1,
        dense3_output_ce1,
        dense3_output_q1,
        maxIndex_out,
        maxIndex_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] dense3_output_address0;
output   dense3_output_ce0;
input  [31:0] dense3_output_q0;
output  [3:0] dense3_output_address1;
output   dense3_output_ce1;
input  [31:0] dense3_output_q1;
output  [31:0] maxIndex_out;
output   maxIndex_out_ap_vld;

reg ap_idle;
reg dense3_output_ce0;
reg dense3_output_ce1;
reg maxIndex_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1079_fu_99_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] i_reg_247;
reg   [31:0] maxIndex_load_1_reg_255;
wire   [63:0] trunc_ln1080_cast_fu_108_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln1080_fu_113_p1;
reg   [31:0] maxIndex_fu_40;
wire   [31:0] maxIndex_4_fu_216_p3;
reg   [31:0] ap_sig_allocacmp_maxIndex_load_1;
wire    ap_loop_init;
reg   [3:0] maxIndex_1_fu_44;
wire   [3:0] add_ln1079_fu_118_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] bitcast_ln1080_fu_129_p1;
wire   [31:0] bitcast_ln1080_1_fu_147_p1;
wire   [7:0] tmp_s_fu_133_p4;
wire   [22:0] trunc_ln1080_fu_143_p1;
wire   [0:0] icmp_ln1080_1_fu_171_p2;
wire   [0:0] icmp_ln1080_fu_165_p2;
wire   [7:0] tmp_20_fu_151_p4;
wire   [22:0] trunc_ln1080_1_fu_161_p1;
wire   [0:0] icmp_ln1080_3_fu_189_p2;
wire   [0:0] icmp_ln1080_2_fu_183_p2;
wire   [0:0] or_ln1080_1_fu_195_p2;
wire   [0:0] or_ln1080_fu_177_p2;
wire   [0:0] and_ln1080_fu_201_p2;
wire   [0:0] tmp_21_fu_80_p2;
wire   [0:0] and_ln1080_1_fu_207_p2;
wire   [31:0] zext_ln1080_1_fu_213_p1;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U128(
    .din0(dense3_output_q1),
    .din1(dense3_output_q0),
    .opcode(5'd2),
    .dout(tmp_21_fu_80_p2)
);

lenet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            maxIndex_1_fu_44 <= 4'd1;
        end else if (((icmp_ln1079_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            maxIndex_1_fu_44 <= add_ln1079_fu_118_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            maxIndex_fu_40 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            maxIndex_fu_40 <= maxIndex_4_fu_216_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_247 <= maxIndex_1_fu_44;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1079_fu_99_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        maxIndex_load_1_reg_255 <= ap_sig_allocacmp_maxIndex_load_1;
    end
end

always @ (*) begin
    if (((icmp_ln1079_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_maxIndex_load_1 = maxIndex_4_fu_216_p3;
    end else begin
        ap_sig_allocacmp_maxIndex_load_1 = maxIndex_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense3_output_ce0 = 1'b1;
    end else begin
        dense3_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense3_output_ce1 = 1'b1;
    end else begin
        dense3_output_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1079_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        maxIndex_out_ap_vld = 1'b1;
    end else begin
        maxIndex_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1079_fu_118_p2 = (maxIndex_1_fu_44 + 4'd1);

assign and_ln1080_1_fu_207_p2 = (tmp_21_fu_80_p2 & and_ln1080_fu_201_p2);

assign and_ln1080_fu_201_p2 = (or_ln1080_fu_177_p2 & or_ln1080_1_fu_195_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln1080_1_fu_147_p1 = dense3_output_q0;

assign bitcast_ln1080_fu_129_p1 = dense3_output_q1;

assign dense3_output_address0 = zext_ln1080_fu_113_p1;

assign dense3_output_address1 = trunc_ln1080_cast_fu_108_p1;

assign icmp_ln1079_fu_99_p2 = ((maxIndex_1_fu_44 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln1080_1_fu_171_p2 = ((trunc_ln1080_fu_143_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1080_2_fu_183_p2 = ((tmp_20_fu_151_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1080_3_fu_189_p2 = ((trunc_ln1080_1_fu_161_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1080_fu_165_p2 = ((tmp_s_fu_133_p4 != 8'd255) ? 1'b1 : 1'b0);

assign maxIndex_4_fu_216_p3 = ((and_ln1080_1_fu_207_p2[0:0] == 1'b1) ? zext_ln1080_1_fu_213_p1 : maxIndex_load_1_reg_255);

assign maxIndex_out = maxIndex_fu_40;

assign or_ln1080_1_fu_195_p2 = (icmp_ln1080_3_fu_189_p2 | icmp_ln1080_2_fu_183_p2);

assign or_ln1080_fu_177_p2 = (icmp_ln1080_fu_165_p2 | icmp_ln1080_1_fu_171_p2);

assign tmp_20_fu_151_p4 = {{bitcast_ln1080_1_fu_147_p1[30:23]}};

assign tmp_s_fu_133_p4 = {{bitcast_ln1080_fu_129_p1[30:23]}};

assign trunc_ln1080_1_fu_161_p1 = bitcast_ln1080_1_fu_147_p1[22:0];

assign trunc_ln1080_cast_fu_108_p1 = maxIndex_1_fu_44;

assign trunc_ln1080_fu_143_p1 = bitcast_ln1080_fu_129_p1[22:0];

assign zext_ln1080_1_fu_213_p1 = i_reg_247;

assign zext_ln1080_fu_113_p1 = ap_sig_allocacmp_maxIndex_load_1;

endmodule //lenet_lenet_Pipeline_VITIS_LOOP_1079_4
