// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_lenet_Pipeline_VITIS_LOOP_80_4_VITIS_LOOP_81_5_VITIS_LOOP_82_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_biases_load,
        select_ln77,
        select_ln77_2,
        zext_ln78,
        select_ln76_1,
        pool1_output_address0,
        pool1_output_ce0,
        pool1_output_q0,
        sum_2_out,
        sum_2_out_ap_vld,
        grp_fu_1072_p_din0,
        grp_fu_1072_p_din1,
        grp_fu_1072_p_opcode,
        grp_fu_1072_p_dout0,
        grp_fu_1072_p_ce,
        grp_fu_1076_p_din0,
        grp_fu_1076_p_din1,
        grp_fu_1076_p_dout0,
        grp_fu_1076_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] conv2_biases_load;
input  [3:0] select_ln77;
input  [3:0] select_ln77_2;
input  [3:0] zext_ln78;
input  [4:0] select_ln76_1;
output  [9:0] pool1_output_address0;
output   pool1_output_ce0;
input  [31:0] pool1_output_q0;
output  [31:0] sum_2_out;
output   sum_2_out_ap_vld;
output  [31:0] grp_fu_1072_p_din0;
output  [31:0] grp_fu_1072_p_din1;
output  [1:0] grp_fu_1072_p_opcode;
input  [31:0] grp_fu_1072_p_dout0;
output   grp_fu_1072_p_ce;
output  [31:0] grp_fu_1076_p_din0;
output  [31:0] grp_fu_1076_p_din1;
input  [31:0] grp_fu_1076_p_dout0;
output   grp_fu_1076_p_ce;

reg ap_idle;
reg pool1_output_ce0;
reg sum_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln80_fu_238_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [11:0] conv2_kernel_address0;
reg    conv2_kernel_ce0;
wire   [31:0] conv2_kernel_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln80_reg_638;
reg   [0:0] icmp_ln80_reg_638_pp0_iter1_reg;
wire   [63:0] zext_ln86_9_fu_521_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln86_10_fu_532_p1;
reg   [31:0] sum_1_fu_90;
reg   [31:0] ap_sig_allocacmp_sum_1_load_1;
wire    ap_loop_init;
reg   [2:0] d_fu_94;
wire   [2:0] add_ln82_fu_537_p2;
reg   [2:0] ap_sig_allocacmp_d_load;
reg   [2:0] l_fu_98;
wire   [2:0] select_ln81_1_fu_399_p3;
reg   [2:0] ap_sig_allocacmp_l_1;
reg   [5:0] indvar_flatten124_fu_102;
wire   [5:0] select_ln81_3_fu_549_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten124_load;
reg   [2:0] k_fu_106;
wire   [2:0] select_ln80_1_fu_279_p3;
reg   [2:0] ap_sig_allocacmp_k_load;
reg   [7:0] indvar_flatten149_fu_110;
wire   [7:0] add_ln80_2_fu_244_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten149_load;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] zext_ln81_fu_228_p1;
wire   [0:0] icmp_ln81_fu_265_p2;
wire   [2:0] add_ln80_fu_259_p2;
wire   [4:0] tmp_s_fu_291_p3;
wire   [5:0] zext_ln86_1_fu_299_p1;
wire   [5:0] zext_ln86_fu_287_p1;
wire   [3:0] zext_ln80_fu_309_p1;
wire   [3:0] add_ln80_1_fu_313_p2;
wire   [7:0] tmp_1_fu_319_p3;
wire   [5:0] tmp_2_fu_331_p3;
wire   [8:0] zext_ln86_2_fu_327_p1;
wire   [8:0] zext_ln86_3_fu_339_p1;
wire   [8:0] sub_ln86_fu_343_p2;
wire   [3:0] empty_fu_232_p2;
wire   [0:0] icmp_ln82_fu_367_p2;
wire   [0:0] xor_ln80_fu_361_p2;
wire   [2:0] select_ln80_fu_271_p3;
wire   [0:0] and_ln80_fu_373_p2;
wire   [0:0] or_ln81_fu_385_p2;
wire   [2:0] add_ln81_fu_379_p2;
wire   [5:0] add_ln86_fu_303_p2;
wire   [5:0] zext_ln86_4_fu_407_p1;
wire   [5:0] add_ln86_1_fu_411_p2;
wire   [4:0] trunc_ln86_fu_417_p1;
wire   [6:0] tmp_fu_429_p3;
wire   [7:0] p_shl32_cast_fu_421_p3;
wire   [7:0] zext_ln86_5_fu_437_p1;
wire   [3:0] zext_ln81_1_fu_447_p1;
wire   [3:0] p_mid1122_fu_451_p2;
wire   [3:0] select_ln80_2_fu_353_p3;
wire   [3:0] select_ln81_2_fu_457_p3;
wire  signed [9:0] sext_ln80_fu_349_p1;
wire   [9:0] zext_ln86_6_fu_465_p1;
wire   [9:0] add_ln86_2_fu_469_p2;
wire   [9:0] shl_ln86_fu_475_p2;
wire   [9:0] shl_ln86_1_fu_481_p2;
wire   [2:0] select_ln81_fu_391_p3;
wire   [7:0] sub_ln86_1_fu_441_p2;
wire   [7:0] zext_ln86_8_fu_497_p1;
wire   [7:0] add_ln86_3_fu_501_p2;
wire   [11:0] tmp_100_cast_fu_507_p3;
wire   [11:0] select_ln76_1_cast_fu_188_p1;
wire   [11:0] add_ln86_4_fu_515_p2;
wire   [9:0] sub_ln86_2_fu_487_p2;
wire   [9:0] zext_ln86_7_fu_493_p1;
wire   [9:0] add_ln86_5_fu_526_p2;
wire   [5:0] add_ln81_1_fu_543_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_lenet_Pipeline_VITIS_LOOP_80_4_VITIS_LOOP_81_5_VITIS_LOOP_82_6_conv2_kernel_RBew #(
    .DataWidth( 32 ),
    .AddressRange( 2400 ),
    .AddressWidth( 12 ))
conv2_kernel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_kernel_address0),
    .ce0(conv2_kernel_ce0),
    .q0(conv2_kernel_q0)
);

lenet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            d_fu_94 <= add_ln82_fu_537_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            d_fu_94 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten124_fu_102 <= select_ln81_3_fu_549_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten124_fu_102 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten149_fu_110 <= add_ln80_2_fu_244_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten149_fu_110 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_106 <= select_ln80_1_fu_279_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_106 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln80_fu_238_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            l_fu_98 <= select_ln81_1_fu_399_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            l_fu_98 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            sum_1_fu_90 <= conv2_biases_load;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            sum_1_fu_90 <= grp_fu_1072_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln80_reg_638 <= icmp_ln80_fu_238_p2;
        icmp_ln80_reg_638_pp0_iter1_reg <= icmp_ln80_reg_638;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_238_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_d_load = 3'd0;
    end else begin
        ap_sig_allocacmp_d_load = d_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten124_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten124_load = indvar_flatten124_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten149_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten149_load = indvar_flatten149_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 3'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_l_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_l_1 = l_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_sum_1_load_1 = grp_fu_1072_p_dout0;
    end else begin
        ap_sig_allocacmp_sum_1_load_1 = sum_1_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_kernel_ce0 = 1'b1;
    end else begin
        conv2_kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_output_ce0 = 1'b1;
    end else begin
        pool1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_638_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_2_out_ap_vld = 1'b1;
    end else begin
        sum_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln80_1_fu_313_p2 = (zext_ln80_fu_309_p1 + select_ln77_2);

assign add_ln80_2_fu_244_p2 = (ap_sig_allocacmp_indvar_flatten149_load + 8'd1);

assign add_ln80_fu_259_p2 = (ap_sig_allocacmp_k_load + 3'd1);

assign add_ln81_1_fu_543_p2 = (ap_sig_allocacmp_indvar_flatten124_load + 6'd1);

assign add_ln81_fu_379_p2 = (select_ln80_fu_271_p3 + 3'd1);

assign add_ln82_fu_537_p2 = (select_ln81_fu_391_p3 + 3'd1);

assign add_ln86_1_fu_411_p2 = (add_ln86_fu_303_p2 + zext_ln86_4_fu_407_p1);

assign add_ln86_2_fu_469_p2 = ($signed(sext_ln80_fu_349_p1) + $signed(zext_ln86_6_fu_465_p1));

assign add_ln86_3_fu_501_p2 = (sub_ln86_1_fu_441_p2 + zext_ln86_8_fu_497_p1);

assign add_ln86_4_fu_515_p2 = (tmp_100_cast_fu_507_p3 + select_ln76_1_cast_fu_188_p1);

assign add_ln86_5_fu_526_p2 = (sub_ln86_2_fu_487_p2 + zext_ln86_7_fu_493_p1);

assign add_ln86_fu_303_p2 = (zext_ln86_1_fu_299_p1 + zext_ln86_fu_287_p1);

assign and_ln80_fu_373_p2 = (xor_ln80_fu_361_p2 & icmp_ln82_fu_367_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv2_kernel_address0 = zext_ln86_9_fu_521_p1;

assign empty_fu_232_p2 = (zext_ln81_fu_228_p1 + select_ln77);

assign grp_fu_1072_p_ce = 1'b1;

assign grp_fu_1072_p_din0 = ap_sig_allocacmp_sum_1_load_1;

assign grp_fu_1072_p_din1 = grp_fu_1076_p_dout0;

assign grp_fu_1072_p_opcode = 2'd0;

assign grp_fu_1076_p_ce = 1'b1;

assign grp_fu_1076_p_din0 = pool1_output_q0;

assign grp_fu_1076_p_din1 = conv2_kernel_q0;

assign icmp_ln80_fu_238_p2 = ((ap_sig_allocacmp_indvar_flatten149_load == 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_265_p2 = ((ap_sig_allocacmp_indvar_flatten124_load == 6'd30) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_367_p2 = ((ap_sig_allocacmp_d_load == 3'd6) ? 1'b1 : 1'b0);

assign or_ln81_fu_385_p2 = (icmp_ln81_fu_265_p2 | and_ln80_fu_373_p2);

assign p_mid1122_fu_451_p2 = (zext_ln81_1_fu_447_p1 + select_ln77);

assign p_shl32_cast_fu_421_p3 = {{trunc_ln86_fu_417_p1}, {3'd0}};

assign pool1_output_address0 = zext_ln86_10_fu_532_p1;

assign select_ln76_1_cast_fu_188_p1 = select_ln76_1;

assign select_ln80_1_fu_279_p3 = ((icmp_ln81_fu_265_p2[0:0] == 1'b1) ? add_ln80_fu_259_p2 : ap_sig_allocacmp_k_load);

assign select_ln80_2_fu_353_p3 = ((icmp_ln81_fu_265_p2[0:0] == 1'b1) ? zext_ln78 : empty_fu_232_p2);

assign select_ln80_fu_271_p3 = ((icmp_ln81_fu_265_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_l_1);

assign select_ln81_1_fu_399_p3 = ((and_ln80_fu_373_p2[0:0] == 1'b1) ? add_ln81_fu_379_p2 : select_ln80_fu_271_p3);

assign select_ln81_2_fu_457_p3 = ((and_ln80_fu_373_p2[0:0] == 1'b1) ? p_mid1122_fu_451_p2 : select_ln80_2_fu_353_p3);

assign select_ln81_3_fu_549_p3 = ((icmp_ln81_fu_265_p2[0:0] == 1'b1) ? 6'd1 : add_ln81_1_fu_543_p2);

assign select_ln81_fu_391_p3 = ((or_ln81_fu_385_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_d_load);

assign sext_ln80_fu_349_p1 = $signed(sub_ln86_fu_343_p2);

assign shl_ln86_1_fu_481_p2 = add_ln86_2_fu_469_p2 << 10'd1;

assign shl_ln86_fu_475_p2 = add_ln86_2_fu_469_p2 << 10'd3;

assign sub_ln86_1_fu_441_p2 = (p_shl32_cast_fu_421_p3 - zext_ln86_5_fu_437_p1);

assign sub_ln86_2_fu_487_p2 = (shl_ln86_fu_475_p2 - shl_ln86_1_fu_481_p2);

assign sub_ln86_fu_343_p2 = (zext_ln86_2_fu_327_p1 - zext_ln86_3_fu_339_p1);

assign sum_2_out = sum_1_fu_90;

assign tmp_100_cast_fu_507_p3 = {{add_ln86_3_fu_501_p2}, {4'd0}};

assign tmp_1_fu_319_p3 = {{add_ln80_1_fu_313_p2}, {4'd0}};

assign tmp_2_fu_331_p3 = {{add_ln80_1_fu_313_p2}, {2'd0}};

assign tmp_fu_429_p3 = {{add_ln86_1_fu_411_p2}, {1'd0}};

assign tmp_s_fu_291_p3 = {{select_ln80_1_fu_279_p3}, {2'd0}};

assign trunc_ln86_fu_417_p1 = add_ln86_1_fu_411_p2[4:0];

assign xor_ln80_fu_361_p2 = (icmp_ln81_fu_265_p2 ^ 1'd1);

assign zext_ln80_fu_309_p1 = select_ln80_1_fu_279_p3;

assign zext_ln81_1_fu_447_p1 = add_ln81_fu_379_p2;

assign zext_ln81_fu_228_p1 = ap_sig_allocacmp_l_1;

assign zext_ln86_10_fu_532_p1 = add_ln86_5_fu_526_p2;

assign zext_ln86_1_fu_299_p1 = tmp_s_fu_291_p3;

assign zext_ln86_2_fu_327_p1 = tmp_1_fu_319_p3;

assign zext_ln86_3_fu_339_p1 = tmp_2_fu_331_p3;

assign zext_ln86_4_fu_407_p1 = select_ln81_1_fu_399_p3;

assign zext_ln86_5_fu_437_p1 = tmp_fu_429_p3;

assign zext_ln86_6_fu_465_p1 = select_ln81_2_fu_457_p3;

assign zext_ln86_7_fu_493_p1 = select_ln81_fu_391_p3;

assign zext_ln86_8_fu_497_p1 = select_ln81_fu_391_p3;

assign zext_ln86_9_fu_521_p1 = add_ln86_4_fu_515_p2;

assign zext_ln86_fu_287_p1 = select_ln80_1_fu_279_p3;

endmodule //lenet_lenet_Pipeline_VITIS_LOOP_80_4_VITIS_LOOP_81_5_VITIS_LOOP_82_6
