// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_lenet_Pipeline_VITIS_LOOP_101_1_VITIS_LOOP_102_2_VITIS_LOOP_103_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool1_output_address0,
        pool1_output_ce0,
        pool1_output_we0,
        pool1_output_d0,
        conv1_output_address0,
        conv1_output_ce0,
        conv1_output_q0,
        conv1_output_address1,
        conv1_output_ce1,
        conv1_output_q1,
        conv1_output_address2,
        conv1_output_ce2,
        conv1_output_q2,
        conv1_output_address3,
        conv1_output_ce3,
        conv1_output_q3
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] pool1_output_address0;
output   pool1_output_ce0;
output   pool1_output_we0;
output  [31:0] pool1_output_d0;
output  [11:0] conv1_output_address0;
output   conv1_output_ce0;
input  [31:0] conv1_output_q0;
output  [11:0] conv1_output_address1;
output   conv1_output_ce1;
input  [31:0] conv1_output_q1;
output  [11:0] conv1_output_address2;
output   conv1_output_ce2;
input  [31:0] conv1_output_q2;
output  [11:0] conv1_output_address3;
output   conv1_output_ce3;
input  [31:0] conv1_output_q3;

reg ap_idle;
reg pool1_output_ce0;
reg pool1_output_we0;
reg conv1_output_ce0;
reg conv1_output_ce1;
reg conv1_output_ce2;
reg conv1_output_ce3;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln101_fu_235_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] add_ln114_1_fu_514_p2;
reg   [9:0] add_ln114_1_reg_1133;
reg   [9:0] add_ln114_1_reg_1133_pp0_iter1_reg;
reg   [9:0] add_ln114_1_reg_1133_pp0_iter2_reg;
reg   [9:0] add_ln114_1_reg_1133_pp0_iter3_reg;
wire   [31:0] select_ln110_fu_817_p3;
reg   [31:0] select_ln110_reg_1158;
reg   [31:0] conv1_output_load_1_reg_1165;
reg   [31:0] conv1_output_load_2_reg_1172;
reg   [31:0] conv1_output_load_2_reg_1172_pp0_iter2_reg;
reg   [31:0] conv1_output_load_3_reg_1179;
reg   [31:0] conv1_output_load_3_reg_1179_pp0_iter2_reg;
reg   [31:0] conv1_output_load_3_reg_1179_pp0_iter3_reg;
wire   [31:0] select_ln110_1_fu_907_p3;
reg   [31:0] select_ln110_1_reg_1186;
wire   [31:0] select_ln110_2_fu_995_p3;
reg   [31:0] select_ln110_2_reg_1193;
wire   [63:0] zext_ln110_5_fu_574_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln110_6_fu_621_p1;
wire   [63:0] zext_ln110_8_fu_678_p1;
wire   [63:0] zext_ln110_9_fu_725_p1;
wire   [63:0] zext_ln114_3_fu_1001_p1;
reg   [3:0] j_2_fu_90;
wire   [3:0] add_ln103_fu_730_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_2_load;
reg   [3:0] i_2_fu_94;
wire   [3:0] select_ln102_1_fu_346_p3;
reg   [3:0] ap_sig_allocacmp_i;
reg   [7:0] indvar_flatten89_fu_98;
wire   [7:0] select_ln102_4_fu_742_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten89_load;
reg   [2:0] d_fu_102;
wire   [2:0] select_ln101_1_fu_276_p3;
reg   [2:0] ap_sig_allocacmp_d_load;
reg   [9:0] indvar_flatten113_fu_106;
wire   [9:0] add_ln101_1_fu_241_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten113_load;
wire   [4:0] tmp_22_fu_221_p3;
wire   [0:0] icmp_ln102_fu_262_p2;
wire   [2:0] add_ln101_fu_256_p2;
wire   [4:0] empty_fu_229_p2;
wire   [0:0] icmp_ln103_fu_314_p2;
wire   [0:0] xor_ln101_fu_308_p2;
wire   [3:0] select_ln101_fu_268_p3;
wire   [0:0] and_ln101_fu_320_p2;
wire   [0:0] or_ln102_fu_332_p2;
wire   [3:0] add_ln102_fu_326_p2;
wire   [7:0] tmp_fu_354_p3;
wire   [5:0] tmp_14_fu_366_p3;
wire   [62:0] zext_ln114_fu_362_p1;
wire   [62:0] zext_ln114_1_fu_374_p1;
wire   [4:0] p_mid_fu_384_p3;
wire   [4:0] select_ln101_2_fu_292_p3;
wire   [4:0] select_ln102_2_fu_392_p3;
wire   [9:0] tmp_15_fu_400_p3;
wire   [7:0] tmp_16_fu_412_p3;
wire   [62:0] zext_ln110_fu_408_p1;
wire   [62:0] zext_ln110_1_fu_420_p1;
wire   [4:0] p_mid187_fu_430_p2;
wire   [4:0] select_ln101_3_fu_300_p3;
wire   [4:0] select_ln102_3_fu_436_p3;
wire   [9:0] tmp_17_fu_444_p3;
wire   [7:0] tmp_18_fu_456_p3;
wire   [62:0] zext_ln110_2_fu_452_p1;
wire   [62:0] zext_ln110_3_fu_464_p1;
wire   [3:0] select_ln102_fu_338_p3;
wire   [62:0] sub_ln114_fu_378_p2;
wire   [62:0] zext_ln114_2_fu_474_p1;
wire   [62:0] add_ln114_fu_478_p2;
wire   [6:0] trunc_ln114_fu_484_p1;
wire   [8:0] trunc_ln114_1_fu_496_p1;
wire   [9:0] p_shl22_cast_fu_488_p3;
wire   [9:0] p_shl23_cast_fu_500_p3;
wire   [9:0] sub_ln114_1_fu_508_p2;
wire   [9:0] zext_ln101_1_fu_288_p1;
wire   [4:0] tmp_23_fu_520_p3;
wire   [62:0] sub_ln110_fu_424_p2;
wire   [62:0] zext_ln110_4_fu_528_p1;
wire   [62:0] add_ln110_fu_532_p2;
wire   [8:0] trunc_ln110_fu_538_p1;
wire   [10:0] trunc_ln110_1_fu_550_p1;
wire   [11:0] p_shl24_cast_fu_542_p3;
wire   [11:0] p_shl25_cast_fu_554_p3;
wire   [11:0] sub_ln110_2_fu_562_p2;
wire   [11:0] zext_ln101_fu_284_p1;
wire   [11:0] add_ln110_1_fu_568_p2;
wire   [62:0] sub_ln110_1_fu_468_p2;
wire   [62:0] add_ln110_2_fu_579_p2;
wire   [8:0] trunc_ln110_2_fu_585_p1;
wire   [10:0] trunc_ln110_3_fu_597_p1;
wire   [11:0] p_shl26_cast_fu_589_p3;
wire   [11:0] p_shl27_cast_fu_601_p3;
wire   [11:0] sub_ln110_3_fu_609_p2;
wire   [11:0] add_ln110_3_fu_615_p2;
wire   [4:0] or_ln108_fu_626_p2;
wire   [62:0] zext_ln110_7_fu_632_p1;
wire   [62:0] add_ln110_4_fu_636_p2;
wire   [8:0] trunc_ln110_4_fu_642_p1;
wire   [10:0] trunc_ln110_5_fu_654_p1;
wire   [11:0] p_shl28_cast_fu_646_p3;
wire   [11:0] p_shl29_cast_fu_658_p3;
wire   [11:0] sub_ln110_4_fu_666_p2;
wire   [11:0] add_ln110_5_fu_672_p2;
wire   [62:0] add_ln110_6_fu_683_p2;
wire   [8:0] trunc_ln110_6_fu_689_p1;
wire   [10:0] trunc_ln110_7_fu_701_p1;
wire   [11:0] p_shl30_cast_fu_693_p3;
wire   [11:0] p_shl31_cast_fu_705_p3;
wire   [11:0] sub_ln110_5_fu_713_p2;
wire   [11:0] add_ln110_7_fu_719_p2;
wire   [7:0] add_ln102_1_fu_736_p2;
wire   [31:0] bitcast_ln224_fu_775_p1;
wire   [7:0] tmp_4_fu_779_p4;
wire   [22:0] trunc_ln224_fu_789_p1;
wire   [0:0] icmp_ln224_1_fu_799_p2;
wire   [0:0] icmp_ln224_fu_793_p2;
wire   [0:0] or_ln224_fu_805_p2;
wire   [0:0] tmp_5_fu_172_p2;
wire   [0:0] and_ln224_fu_811_p2;
wire   [31:0] bitcast_ln224_1_fu_825_p1;
wire   [31:0] bitcast_ln224_2_fu_842_p1;
wire   [7:0] tmp_6_fu_828_p4;
wire   [22:0] trunc_ln224_7_fu_838_p1;
wire   [0:0] icmp_ln224_3_fu_865_p2;
wire   [0:0] icmp_ln224_2_fu_859_p2;
wire   [7:0] tmp_7_fu_845_p4;
wire   [22:0] trunc_ln224_8_fu_855_p1;
wire   [0:0] icmp_ln224_5_fu_883_p2;
wire   [0:0] icmp_ln224_4_fu_877_p2;
wire   [0:0] or_ln224_1_fu_871_p2;
wire   [0:0] or_ln224_2_fu_889_p2;
wire   [0:0] and_ln224_1_fu_895_p2;
wire   [0:0] tmp_8_fu_178_p2;
wire   [0:0] and_ln224_2_fu_901_p2;
wire   [31:0] bitcast_ln224_3_fu_913_p1;
wire   [31:0] bitcast_ln224_4_fu_930_p1;
wire   [7:0] tmp_9_fu_916_p4;
wire   [22:0] trunc_ln224_9_fu_926_p1;
wire   [0:0] icmp_ln224_7_fu_953_p2;
wire   [0:0] icmp_ln224_6_fu_947_p2;
wire   [7:0] tmp_s_fu_933_p4;
wire   [22:0] trunc_ln224_10_fu_943_p1;
wire   [0:0] icmp_ln224_9_fu_971_p2;
wire   [0:0] icmp_ln224_8_fu_965_p2;
wire   [0:0] or_ln224_3_fu_959_p2;
wire   [0:0] or_ln224_4_fu_977_p2;
wire   [0:0] and_ln224_3_fu_983_p2;
wire   [0:0] tmp_10_fu_182_p2;
wire   [0:0] and_ln224_4_fu_989_p2;
wire   [31:0] bitcast_ln224_5_fu_1005_p1;
wire   [31:0] bitcast_ln224_6_fu_1022_p1;
wire   [7:0] tmp_11_fu_1008_p4;
wire   [22:0] trunc_ln224_11_fu_1018_p1;
wire   [0:0] icmp_ln224_11_fu_1045_p2;
wire   [0:0] icmp_ln224_10_fu_1039_p2;
wire   [7:0] tmp_12_fu_1025_p4;
wire   [22:0] trunc_ln224_12_fu_1035_p1;
wire   [0:0] icmp_ln224_13_fu_1063_p2;
wire   [0:0] icmp_ln224_12_fu_1057_p2;
wire   [0:0] or_ln224_5_fu_1051_p2;
wire   [0:0] or_ln224_6_fu_1069_p2;
wire   [0:0] and_ln224_5_fu_1075_p2;
wire   [0:0] tmp_13_fu_186_p2;
wire   [0:0] and_ln224_6_fu_1081_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U69(
    .din0(conv1_output_q3),
    .din1(32'd4286578688),
    .opcode(5'd2),
    .dout(tmp_5_fu_172_p2)
);

lenet_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U70(
    .din0(select_ln110_reg_1158),
    .din1(conv1_output_load_1_reg_1165),
    .opcode(5'd4),
    .dout(tmp_8_fu_178_p2)
);

lenet_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U71(
    .din0(select_ln110_1_reg_1186),
    .din1(conv1_output_load_2_reg_1172_pp0_iter2_reg),
    .opcode(5'd4),
    .dout(tmp_10_fu_182_p2)
);

lenet_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U72(
    .din0(select_ln110_2_reg_1193),
    .din1(conv1_output_load_3_reg_1179_pp0_iter3_reg),
    .opcode(5'd4),
    .dout(tmp_13_fu_186_p2)
);

lenet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            d_fu_102 <= select_ln101_1_fu_276_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            d_fu_102 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_2_fu_94 <= select_ln102_1_fu_346_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_94 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten113_fu_106 <= add_ln101_1_fu_241_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten113_fu_106 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten89_fu_98 <= select_ln102_4_fu_742_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten89_fu_98 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln101_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_2_fu_90 <= add_ln103_fu_730_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_2_fu_90 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln101_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln114_1_reg_1133 <= add_ln114_1_fu_514_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln114_1_reg_1133_pp0_iter1_reg <= add_ln114_1_reg_1133;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln110_reg_1158 <= select_ln110_fu_817_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln114_1_reg_1133_pp0_iter2_reg <= add_ln114_1_reg_1133_pp0_iter1_reg;
        add_ln114_1_reg_1133_pp0_iter3_reg <= add_ln114_1_reg_1133_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        conv1_output_load_2_reg_1172_pp0_iter2_reg <= conv1_output_load_2_reg_1172;
        conv1_output_load_3_reg_1179_pp0_iter2_reg <= conv1_output_load_3_reg_1179;
        conv1_output_load_3_reg_1179_pp0_iter3_reg <= conv1_output_load_3_reg_1179_pp0_iter2_reg;
        select_ln110_1_reg_1186 <= select_ln110_1_fu_907_p3;
        select_ln110_2_reg_1193 <= select_ln110_2_fu_995_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_load_1_reg_1165 <= conv1_output_q2;
        conv1_output_load_2_reg_1172 <= conv1_output_q1;
        conv1_output_load_3_reg_1179 <= conv1_output_q0;
    end
end

always @ (*) begin
    if (((icmp_ln101_fu_235_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_d_load = 3'd0;
    end else begin
        ap_sig_allocacmp_d_load = d_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten113_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten113_load = indvar_flatten113_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten89_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten89_load = indvar_flatten89_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_2_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_2_load = j_2_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce0 = 1'b1;
    end else begin
        conv1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce1 = 1'b1;
    end else begin
        conv1_output_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce2 = 1'b1;
    end else begin
        conv1_output_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_output_ce3 = 1'b1;
    end else begin
        conv1_output_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pool1_output_ce0 = 1'b1;
    end else begin
        pool1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        pool1_output_we0 = 1'b1;
    end else begin
        pool1_output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_1_fu_241_p2 = (ap_sig_allocacmp_indvar_flatten113_load + 10'd1);

assign add_ln101_fu_256_p2 = (ap_sig_allocacmp_d_load + 3'd1);

assign add_ln102_1_fu_736_p2 = (ap_sig_allocacmp_indvar_flatten89_load + 8'd1);

assign add_ln102_fu_326_p2 = (select_ln101_fu_268_p3 + 4'd1);

assign add_ln103_fu_730_p2 = (select_ln102_fu_338_p3 + 4'd1);

assign add_ln110_1_fu_568_p2 = (sub_ln110_2_fu_562_p2 + zext_ln101_fu_284_p1);

assign add_ln110_2_fu_579_p2 = (sub_ln110_1_fu_468_p2 + zext_ln110_4_fu_528_p1);

assign add_ln110_3_fu_615_p2 = (sub_ln110_3_fu_609_p2 + zext_ln101_fu_284_p1);

assign add_ln110_4_fu_636_p2 = (sub_ln110_fu_424_p2 + zext_ln110_7_fu_632_p1);

assign add_ln110_5_fu_672_p2 = (sub_ln110_4_fu_666_p2 + zext_ln101_fu_284_p1);

assign add_ln110_6_fu_683_p2 = (sub_ln110_1_fu_468_p2 + zext_ln110_7_fu_632_p1);

assign add_ln110_7_fu_719_p2 = (sub_ln110_5_fu_713_p2 + zext_ln101_fu_284_p1);

assign add_ln110_fu_532_p2 = (sub_ln110_fu_424_p2 + zext_ln110_4_fu_528_p1);

assign add_ln114_1_fu_514_p2 = (sub_ln114_1_fu_508_p2 + zext_ln101_1_fu_288_p1);

assign add_ln114_fu_478_p2 = (sub_ln114_fu_378_p2 + zext_ln114_2_fu_474_p1);

assign and_ln101_fu_320_p2 = (xor_ln101_fu_308_p2 & icmp_ln103_fu_314_p2);

assign and_ln224_1_fu_895_p2 = (or_ln224_2_fu_889_p2 & or_ln224_1_fu_871_p2);

assign and_ln224_2_fu_901_p2 = (tmp_8_fu_178_p2 & and_ln224_1_fu_895_p2);

assign and_ln224_3_fu_983_p2 = (or_ln224_4_fu_977_p2 & or_ln224_3_fu_959_p2);

assign and_ln224_4_fu_989_p2 = (tmp_10_fu_182_p2 & and_ln224_3_fu_983_p2);

assign and_ln224_5_fu_1075_p2 = (or_ln224_6_fu_1069_p2 & or_ln224_5_fu_1051_p2);

assign and_ln224_6_fu_1081_p2 = (tmp_13_fu_186_p2 & and_ln224_5_fu_1075_p2);

assign and_ln224_fu_811_p2 = (tmp_5_fu_172_p2 & or_ln224_fu_805_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln224_1_fu_825_p1 = select_ln110_reg_1158;

assign bitcast_ln224_2_fu_842_p1 = conv1_output_load_1_reg_1165;

assign bitcast_ln224_3_fu_913_p1 = select_ln110_1_reg_1186;

assign bitcast_ln224_4_fu_930_p1 = conv1_output_load_2_reg_1172_pp0_iter2_reg;

assign bitcast_ln224_5_fu_1005_p1 = select_ln110_2_reg_1193;

assign bitcast_ln224_6_fu_1022_p1 = conv1_output_load_3_reg_1179_pp0_iter3_reg;

assign bitcast_ln224_fu_775_p1 = conv1_output_q3;

assign conv1_output_address0 = zext_ln110_9_fu_725_p1;

assign conv1_output_address1 = zext_ln110_6_fu_621_p1;

assign conv1_output_address2 = zext_ln110_8_fu_678_p1;

assign conv1_output_address3 = zext_ln110_5_fu_574_p1;

assign empty_fu_229_p2 = (tmp_22_fu_221_p3 | 5'd1);

assign icmp_ln101_fu_235_p2 = ((ap_sig_allocacmp_indvar_flatten113_load == 10'd864) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_262_p2 = ((ap_sig_allocacmp_indvar_flatten89_load == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln103_fu_314_p2 = ((ap_sig_allocacmp_j_2_load == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln224_10_fu_1039_p2 = ((tmp_11_fu_1008_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_11_fu_1045_p2 = ((trunc_ln224_11_fu_1018_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_12_fu_1057_p2 = ((tmp_12_fu_1025_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_13_fu_1063_p2 = ((trunc_ln224_12_fu_1035_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_1_fu_799_p2 = ((trunc_ln224_fu_789_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_2_fu_859_p2 = ((tmp_6_fu_828_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_3_fu_865_p2 = ((trunc_ln224_7_fu_838_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_4_fu_877_p2 = ((tmp_7_fu_845_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_5_fu_883_p2 = ((trunc_ln224_8_fu_855_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_6_fu_947_p2 = ((tmp_9_fu_916_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_7_fu_953_p2 = ((trunc_ln224_9_fu_926_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_8_fu_965_p2 = ((tmp_s_fu_933_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_9_fu_971_p2 = ((trunc_ln224_10_fu_943_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_793_p2 = ((tmp_4_fu_779_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln102_fu_332_p2 = (icmp_ln102_fu_262_p2 | and_ln101_fu_320_p2);

assign or_ln108_fu_626_p2 = (tmp_23_fu_520_p3 | 5'd1);

assign or_ln224_1_fu_871_p2 = (icmp_ln224_3_fu_865_p2 | icmp_ln224_2_fu_859_p2);

assign or_ln224_2_fu_889_p2 = (icmp_ln224_5_fu_883_p2 | icmp_ln224_4_fu_877_p2);

assign or_ln224_3_fu_959_p2 = (icmp_ln224_7_fu_953_p2 | icmp_ln224_6_fu_947_p2);

assign or_ln224_4_fu_977_p2 = (icmp_ln224_9_fu_971_p2 | icmp_ln224_8_fu_965_p2);

assign or_ln224_5_fu_1051_p2 = (icmp_ln224_11_fu_1045_p2 | icmp_ln224_10_fu_1039_p2);

assign or_ln224_6_fu_1069_p2 = (icmp_ln224_13_fu_1063_p2 | icmp_ln224_12_fu_1057_p2);

assign or_ln224_fu_805_p2 = (icmp_ln224_fu_793_p2 | icmp_ln224_1_fu_799_p2);

assign p_mid187_fu_430_p2 = (p_mid_fu_384_p3 | 5'd1);

assign p_mid_fu_384_p3 = {{add_ln102_fu_326_p2}, {1'd0}};

assign p_shl22_cast_fu_488_p3 = {{trunc_ln114_fu_484_p1}, {3'd0}};

assign p_shl23_cast_fu_500_p3 = {{trunc_ln114_1_fu_496_p1}, {1'd0}};

assign p_shl24_cast_fu_542_p3 = {{trunc_ln110_fu_538_p1}, {3'd0}};

assign p_shl25_cast_fu_554_p3 = {{trunc_ln110_1_fu_550_p1}, {1'd0}};

assign p_shl26_cast_fu_589_p3 = {{trunc_ln110_2_fu_585_p1}, {3'd0}};

assign p_shl27_cast_fu_601_p3 = {{trunc_ln110_3_fu_597_p1}, {1'd0}};

assign p_shl28_cast_fu_646_p3 = {{trunc_ln110_4_fu_642_p1}, {3'd0}};

assign p_shl29_cast_fu_658_p3 = {{trunc_ln110_5_fu_654_p1}, {1'd0}};

assign p_shl30_cast_fu_693_p3 = {{trunc_ln110_6_fu_689_p1}, {3'd0}};

assign p_shl31_cast_fu_705_p3 = {{trunc_ln110_7_fu_701_p1}, {1'd0}};

assign pool1_output_address0 = zext_ln114_3_fu_1001_p1;

assign pool1_output_d0 = ((and_ln224_6_fu_1081_p2[0:0] == 1'b1) ? conv1_output_load_3_reg_1179_pp0_iter3_reg : select_ln110_2_reg_1193);

assign select_ln101_1_fu_276_p3 = ((icmp_ln102_fu_262_p2[0:0] == 1'b1) ? add_ln101_fu_256_p2 : ap_sig_allocacmp_d_load);

assign select_ln101_2_fu_292_p3 = ((icmp_ln102_fu_262_p2[0:0] == 1'b1) ? 5'd0 : tmp_22_fu_221_p3);

assign select_ln101_3_fu_300_p3 = ((icmp_ln102_fu_262_p2[0:0] == 1'b1) ? 5'd1 : empty_fu_229_p2);

assign select_ln101_fu_268_p3 = ((icmp_ln102_fu_262_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_i);

assign select_ln102_1_fu_346_p3 = ((and_ln101_fu_320_p2[0:0] == 1'b1) ? add_ln102_fu_326_p2 : select_ln101_fu_268_p3);

assign select_ln102_2_fu_392_p3 = ((and_ln101_fu_320_p2[0:0] == 1'b1) ? p_mid_fu_384_p3 : select_ln101_2_fu_292_p3);

assign select_ln102_3_fu_436_p3 = ((and_ln101_fu_320_p2[0:0] == 1'b1) ? p_mid187_fu_430_p2 : select_ln101_3_fu_300_p3);

assign select_ln102_4_fu_742_p3 = ((icmp_ln102_fu_262_p2[0:0] == 1'b1) ? 8'd1 : add_ln102_1_fu_736_p2);

assign select_ln102_fu_338_p3 = ((or_ln102_fu_332_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_2_load);

assign select_ln110_1_fu_907_p3 = ((and_ln224_2_fu_901_p2[0:0] == 1'b1) ? conv1_output_load_1_reg_1165 : select_ln110_reg_1158);

assign select_ln110_2_fu_995_p3 = ((and_ln224_4_fu_989_p2[0:0] == 1'b1) ? conv1_output_load_2_reg_1172_pp0_iter2_reg : select_ln110_1_reg_1186);

assign select_ln110_fu_817_p3 = ((and_ln224_fu_811_p2[0:0] == 1'b1) ? conv1_output_q3 : 32'd4286578688);

assign sub_ln110_1_fu_468_p2 = (zext_ln110_2_fu_452_p1 - zext_ln110_3_fu_464_p1);

assign sub_ln110_2_fu_562_p2 = (p_shl24_cast_fu_542_p3 - p_shl25_cast_fu_554_p3);

assign sub_ln110_3_fu_609_p2 = (p_shl26_cast_fu_589_p3 - p_shl27_cast_fu_601_p3);

assign sub_ln110_4_fu_666_p2 = (p_shl28_cast_fu_646_p3 - p_shl29_cast_fu_658_p3);

assign sub_ln110_5_fu_713_p2 = (p_shl30_cast_fu_693_p3 - p_shl31_cast_fu_705_p3);

assign sub_ln110_fu_424_p2 = (zext_ln110_fu_408_p1 - zext_ln110_1_fu_420_p1);

assign sub_ln114_1_fu_508_p2 = (p_shl22_cast_fu_488_p3 - p_shl23_cast_fu_500_p3);

assign sub_ln114_fu_378_p2 = (zext_ln114_fu_362_p1 - zext_ln114_1_fu_374_p1);

assign tmp_11_fu_1008_p4 = {{bitcast_ln224_5_fu_1005_p1[30:23]}};

assign tmp_12_fu_1025_p4 = {{bitcast_ln224_6_fu_1022_p1[30:23]}};

assign tmp_14_fu_366_p3 = {{select_ln102_1_fu_346_p3}, {2'd0}};

assign tmp_15_fu_400_p3 = {{select_ln102_2_fu_392_p3}, {5'd0}};

assign tmp_16_fu_412_p3 = {{select_ln102_2_fu_392_p3}, {3'd0}};

assign tmp_17_fu_444_p3 = {{select_ln102_3_fu_436_p3}, {5'd0}};

assign tmp_18_fu_456_p3 = {{select_ln102_3_fu_436_p3}, {3'd0}};

assign tmp_22_fu_221_p3 = {{ap_sig_allocacmp_i}, {1'd0}};

assign tmp_23_fu_520_p3 = {{select_ln102_fu_338_p3}, {1'd0}};

assign tmp_4_fu_779_p4 = {{bitcast_ln224_fu_775_p1[30:23]}};

assign tmp_6_fu_828_p4 = {{bitcast_ln224_1_fu_825_p1[30:23]}};

assign tmp_7_fu_845_p4 = {{bitcast_ln224_2_fu_842_p1[30:23]}};

assign tmp_9_fu_916_p4 = {{bitcast_ln224_3_fu_913_p1[30:23]}};

assign tmp_fu_354_p3 = {{select_ln102_1_fu_346_p3}, {4'd0}};

assign tmp_s_fu_933_p4 = {{bitcast_ln224_4_fu_930_p1[30:23]}};

assign trunc_ln110_1_fu_550_p1 = add_ln110_fu_532_p2[10:0];

assign trunc_ln110_2_fu_585_p1 = add_ln110_2_fu_579_p2[8:0];

assign trunc_ln110_3_fu_597_p1 = add_ln110_2_fu_579_p2[10:0];

assign trunc_ln110_4_fu_642_p1 = add_ln110_4_fu_636_p2[8:0];

assign trunc_ln110_5_fu_654_p1 = add_ln110_4_fu_636_p2[10:0];

assign trunc_ln110_6_fu_689_p1 = add_ln110_6_fu_683_p2[8:0];

assign trunc_ln110_7_fu_701_p1 = add_ln110_6_fu_683_p2[10:0];

assign trunc_ln110_fu_538_p1 = add_ln110_fu_532_p2[8:0];

assign trunc_ln114_1_fu_496_p1 = add_ln114_fu_478_p2[8:0];

assign trunc_ln114_fu_484_p1 = add_ln114_fu_478_p2[6:0];

assign trunc_ln224_10_fu_943_p1 = bitcast_ln224_4_fu_930_p1[22:0];

assign trunc_ln224_11_fu_1018_p1 = bitcast_ln224_5_fu_1005_p1[22:0];

assign trunc_ln224_12_fu_1035_p1 = bitcast_ln224_6_fu_1022_p1[22:0];

assign trunc_ln224_7_fu_838_p1 = bitcast_ln224_1_fu_825_p1[22:0];

assign trunc_ln224_8_fu_855_p1 = bitcast_ln224_2_fu_842_p1[22:0];

assign trunc_ln224_9_fu_926_p1 = bitcast_ln224_3_fu_913_p1[22:0];

assign trunc_ln224_fu_789_p1 = bitcast_ln224_fu_775_p1[22:0];

assign xor_ln101_fu_308_p2 = (icmp_ln102_fu_262_p2 ^ 1'd1);

assign zext_ln101_1_fu_288_p1 = select_ln101_1_fu_276_p3;

assign zext_ln101_fu_284_p1 = select_ln101_1_fu_276_p3;

assign zext_ln110_1_fu_420_p1 = tmp_16_fu_412_p3;

assign zext_ln110_2_fu_452_p1 = tmp_17_fu_444_p3;

assign zext_ln110_3_fu_464_p1 = tmp_18_fu_456_p3;

assign zext_ln110_4_fu_528_p1 = tmp_23_fu_520_p3;

assign zext_ln110_5_fu_574_p1 = add_ln110_1_fu_568_p2;

assign zext_ln110_6_fu_621_p1 = add_ln110_3_fu_615_p2;

assign zext_ln110_7_fu_632_p1 = or_ln108_fu_626_p2;

assign zext_ln110_8_fu_678_p1 = add_ln110_5_fu_672_p2;

assign zext_ln110_9_fu_725_p1 = add_ln110_7_fu_719_p2;

assign zext_ln110_fu_408_p1 = tmp_15_fu_400_p3;

assign zext_ln114_1_fu_374_p1 = tmp_14_fu_366_p3;

assign zext_ln114_2_fu_474_p1 = select_ln102_fu_338_p3;

assign zext_ln114_3_fu_1001_p1 = add_ln114_1_reg_1133_pp0_iter3_reg;

assign zext_ln114_fu_362_p1 = tmp_fu_354_p3;

endmodule //lenet_lenet_Pipeline_VITIS_LOOP_101_1_VITIS_LOOP_102_2_VITIS_LOOP_103_3
