// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_lenet_Pipeline_VITIS_LOOP_182_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dense2_biases_load,
        dense2_output_address0,
        dense2_output_ce0,
        dense2_output_we0,
        dense2_output_d0,
        zext_ln180,
        dense1_output_address0,
        dense1_output_ce0,
        dense1_output_q0,
        grp_fu_1072_p_din0,
        grp_fu_1072_p_din1,
        grp_fu_1072_p_opcode,
        grp_fu_1072_p_dout0,
        grp_fu_1072_p_ce,
        grp_fu_1076_p_din0,
        grp_fu_1076_p_din1,
        grp_fu_1076_p_dout0,
        grp_fu_1076_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] dense2_biases_load;
output  [6:0] dense2_output_address0;
output   dense2_output_ce0;
output   dense2_output_we0;
output  [31:0] dense2_output_d0;
input  [6:0] zext_ln180;
output  [6:0] dense1_output_address0;
output   dense1_output_ce0;
input  [31:0] dense1_output_q0;
output  [31:0] grp_fu_1072_p_din0;
output  [31:0] grp_fu_1072_p_din1;
output  [1:0] grp_fu_1072_p_opcode;
input  [31:0] grp_fu_1072_p_dout0;
output   grp_fu_1072_p_ce;
output  [31:0] grp_fu_1076_p_din0;
output  [31:0] grp_fu_1076_p_din1;
input  [31:0] grp_fu_1076_p_dout0;
output   grp_fu_1076_p_ce;

reg ap_idle;
reg dense2_output_ce0;
reg dense2_output_we0;
reg dense1_output_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln182_fu_161_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [13:0] dense2_weights_address0;
reg    dense2_weights_ce0;
wire   [31:0] dense2_weights_q0;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] dense2_output_addr_reg_293;
reg   [6:0] dense2_output_addr_reg_293_pp0_iter1_reg;
reg   [6:0] dense2_output_addr_reg_293_pp0_iter2_reg;
reg   [6:0] dense2_output_addr_reg_293_pp0_iter3_reg;
wire   [0:0] ifzero238_fu_198_p2;
reg   [0:0] ifzero238_reg_312;
reg   [0:0] ifzero238_reg_312_pp0_iter1_reg;
reg   [0:0] ifzero238_reg_312_pp0_iter2_reg;
reg   [0:0] ifzero238_reg_312_pp0_iter3_reg;
reg   [31:0] x_assign_reg_336;
wire   [63:0] zext_ln180_cast1_fu_134_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln183_fu_193_p1;
wire   [63:0] j_7_cast_fu_176_p1;
reg   [13:0] phi_mul_fu_56;
wire   [13:0] add_ln183_1_fu_181_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_phi_mul_load;
reg   [31:0] add56_i126_fu_60;
reg   [31:0] ap_sig_allocacmp_add56_i126_load;
reg   [6:0] j_fu_64;
wire   [6:0] add_ln182_fu_167_p2;
reg   [6:0] ap_sig_allocacmp_j_2;
wire   [13:0] zext_ln180_cast_fu_139_p1;
wire   [13:0] add_ln183_fu_187_p2;
wire   [31:0] bitcast_ln32_fu_223_p1;
wire   [7:0] tmp_s_fu_226_p4;
wire   [22:0] trunc_ln32_fu_236_p1;
wire   [0:0] icmp_ln32_3_fu_246_p2;
wire   [0:0] icmp_ln32_fu_240_p2;
wire   [0:0] or_ln32_fu_252_p2;
wire   [0:0] tmp_7_fu_129_p2;
wire   [0:0] and_ln32_fu_258_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_lenet_Pipeline_VITIS_LOOP_182_2_dense2_weights_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 10080 ),
    .AddressWidth( 14 ))
dense2_weights_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense2_weights_address0),
    .ce0(dense2_weights_ce0),
    .q0(dense2_weights_q0)
);

lenet_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U103(
    .din0(x_assign_reg_336),
    .din1(32'd0),
    .opcode(5'd2),
    .dout(tmp_7_fu_129_p2)
);

lenet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            add56_i126_fu_60 <= dense2_biases_load;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            add56_i126_fu_60 <= grp_fu_1072_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln182_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_64 <= add_ln182_fu_167_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln182_fu_161_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_mul_fu_56 <= add_ln183_1_fu_181_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_56 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        dense2_output_addr_reg_293 <= zext_ln180_cast1_fu_134_p1;
        dense2_output_addr_reg_293_pp0_iter1_reg <= dense2_output_addr_reg_293;
        ifzero238_reg_312_pp0_iter1_reg <= ifzero238_reg_312;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        dense2_output_addr_reg_293_pp0_iter2_reg <= dense2_output_addr_reg_293_pp0_iter1_reg;
        dense2_output_addr_reg_293_pp0_iter3_reg <= dense2_output_addr_reg_293_pp0_iter2_reg;
        ifzero238_reg_312_pp0_iter2_reg <= ifzero238_reg_312_pp0_iter1_reg;
        ifzero238_reg_312_pp0_iter3_reg <= ifzero238_reg_312_pp0_iter2_reg;
        x_assign_reg_336 <= grp_fu_1072_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln182_fu_161_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ifzero238_reg_312 <= ifzero238_fu_198_p2;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_add56_i126_load = grp_fu_1072_p_dout0;
    end else begin
        ap_sig_allocacmp_add56_i126_load = add56_i126_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_mul_load = 14'd0;
    end else begin
        ap_sig_allocacmp_phi_mul_load = phi_mul_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense1_output_ce0 = 1'b1;
    end else begin
        dense1_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        dense2_output_ce0 = 1'b1;
    end else begin
        dense2_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ifzero238_reg_312_pp0_iter3_reg == 1'd1))) begin
        dense2_output_we0 = 1'b1;
    end else begin
        dense2_output_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense2_weights_ce0 = 1'b1;
    end else begin
        dense2_weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln182_fu_167_p2 = (ap_sig_allocacmp_j_2 + 7'd1);

assign add_ln183_1_fu_181_p2 = (ap_sig_allocacmp_phi_mul_load + 14'd84);

assign add_ln183_fu_187_p2 = (ap_sig_allocacmp_phi_mul_load + zext_ln180_cast_fu_139_p1);

assign and_ln32_fu_258_p2 = (tmp_7_fu_129_p2 & or_ln32_fu_252_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln32_fu_223_p1 = x_assign_reg_336;

assign dense1_output_address0 = j_7_cast_fu_176_p1;

assign dense2_output_address0 = dense2_output_addr_reg_293_pp0_iter3_reg;

assign dense2_output_d0 = ((and_ln32_fu_258_p2[0:0] == 1'b1) ? x_assign_reg_336 : 32'd0);

assign dense2_weights_address0 = zext_ln183_fu_193_p1;

assign grp_fu_1072_p_ce = 1'b1;

assign grp_fu_1072_p_din0 = ap_sig_allocacmp_add56_i126_load;

assign grp_fu_1072_p_din1 = grp_fu_1076_p_dout0;

assign grp_fu_1072_p_opcode = 2'd0;

assign grp_fu_1076_p_ce = 1'b1;

assign grp_fu_1076_p_din0 = dense1_output_q0;

assign grp_fu_1076_p_din1 = dense2_weights_q0;

assign icmp_ln182_fu_161_p2 = ((ap_sig_allocacmp_j_2 == 7'd120) ? 1'b1 : 1'b0);

assign icmp_ln32_3_fu_246_p2 = ((trunc_ln32_fu_236_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_240_p2 = ((tmp_s_fu_226_p4 != 8'd255) ? 1'b1 : 1'b0);

assign ifzero238_fu_198_p2 = ((add_ln182_fu_167_p2 == 7'd120) ? 1'b1 : 1'b0);

assign j_7_cast_fu_176_p1 = ap_sig_allocacmp_j_2;

assign or_ln32_fu_252_p2 = (icmp_ln32_fu_240_p2 | icmp_ln32_3_fu_246_p2);

assign tmp_s_fu_226_p4 = {{bitcast_ln32_fu_223_p1[30:23]}};

assign trunc_ln32_fu_236_p1 = bitcast_ln32_fu_223_p1[22:0];

assign zext_ln180_cast1_fu_134_p1 = zext_ln180;

assign zext_ln180_cast_fu_139_p1 = zext_ln180;

assign zext_ln183_fu_193_p1 = add_ln183_fu_187_p2;

endmodule //lenet_lenet_Pipeline_VITIS_LOOP_182_2
