// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lenet_lenet_Pipeline_VITIS_LOOP_148_1_VITIS_LOOP_149_2_VITIS_LOOP_150_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool2_output_address0,
        pool2_output_ce0,
        pool2_output_q0,
        flattened_output_address0,
        flattened_output_ce0,
        flattened_output_we0,
        flattened_output_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] pool2_output_address0;
output   pool2_output_ce0;
input  [31:0] pool2_output_q0;
output  [7:0] flattened_output_address0;
output   flattened_output_ce0;
output   flattened_output_we0;
output  [31:0] flattened_output_d0;

reg ap_idle;
reg pool2_output_ce0;
reg flattened_output_ce0;
reg flattened_output_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln148_fu_166_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln149_fu_196_p2;
reg   [0:0] icmp_ln149_reg_495;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln148_fu_242_p2;
reg   [0:0] and_ln148_reg_502;
wire   [63:0] zext_ln151_2_fu_304_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] index_1_cast_fu_410_p1;
reg   [4:0] d_fu_64;
wire   [4:0] add_ln150_fu_309_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_d_load;
reg   [8:0] index_1_fu_68;
wire   [8:0] add_ln151_fu_415_p2;
reg   [2:0] j_fu_72;
wire   [2:0] select_ln149_2_fu_268_p3;
reg   [2:0] ap_sig_allocacmp_j_load;
reg   [8:0] index_fu_76;
wire   [8:0] select_ln149_3_fu_403_p3;
reg   [7:0] indvar_flatten216_fu_80;
wire   [7:0] select_ln149_4_fu_321_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten216_load;
reg   [2:0] i_fu_84;
wire   [2:0] select_ln148_3_fu_210_p3;
reg   [2:0] ap_sig_allocacmp_i_load;
reg   [8:0] indvars_iv308_fu_88;
wire   [8:0] select_ln148_4_fu_383_p3;
reg   [8:0] indvar_flatten232_fu_92;
wire   [8:0] add_ln148_2_fu_172_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten232_load;
wire   [2:0] add_ln148_fu_190_p2;
wire   [1:0] trunc_ln151_fu_218_p1;
wire   [0:0] icmp_ln150_fu_236_p2;
wire   [0:0] xor_ln148_fu_230_p2;
wire   [2:0] select_ln148_1_fu_202_p3;
wire   [0:0] or_ln149_fu_254_p2;
wire   [2:0] add_ln149_fu_248_p2;
wire   [3:0] tmp_101_cast_fu_222_p3;
wire   [3:0] zext_ln151_fu_276_p1;
wire   [3:0] add_ln151_1_fu_280_p2;
wire   [4:0] select_ln149_1_fu_260_p3;
wire   [7:0] tmp_103_cast_fu_286_p3;
wire   [7:0] zext_ln151_1_fu_294_p1;
wire   [7:0] add_ln151_2_fu_298_p2;
wire   [7:0] add_ln149_2_fu_315_p2;
wire   [8:0] add_ln148_1_fu_363_p2;
wire   [8:0] select_ln148_fu_369_p3;
wire   [8:0] add_ln149_1_fu_390_p2;
wire   [8:0] select_ln148_2_fu_376_p3;
wire   [8:0] select_ln149_fu_396_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

lenet_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln148_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            d_fu_64 <= add_ln150_fu_309_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            d_fu_64 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln148_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_84 <= select_ln148_3_fu_210_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            index_1_fu_68 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            index_1_fu_68 <= add_ln151_fu_415_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            index_fu_76 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            index_fu_76 <= select_ln149_3_fu_403_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln148_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten216_fu_80 <= select_ln149_4_fu_321_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten216_fu_80 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln148_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten232_fu_92 <= add_ln148_2_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten232_fu_92 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvars_iv308_fu_88 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvars_iv308_fu_88 <= select_ln148_4_fu_383_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln148_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_72 <= select_ln149_2_fu_268_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln148_fu_166_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln148_reg_502 <= and_ln148_fu_242_p2;
        icmp_ln149_reg_495 <= icmp_ln149_fu_196_p2;
    end
end

always @ (*) begin
    if (((icmp_ln148_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_d_load = 5'd0;
    end else begin
        ap_sig_allocacmp_d_load = d_fu_64;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_84;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten216_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten216_load = indvar_flatten216_fu_80;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten232_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten232_load = indvar_flatten232_fu_92;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flattened_output_ce0 = 1'b1;
    end else begin
        flattened_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flattened_output_we0 = 1'b1;
    end else begin
        flattened_output_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool2_output_ce0 = 1'b1;
    end else begin
        pool2_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln148_1_fu_363_p2 = (indvars_iv308_fu_88 + 9'd64);

assign add_ln148_2_fu_172_p2 = (ap_sig_allocacmp_indvar_flatten232_load + 9'd1);

assign add_ln148_fu_190_p2 = (ap_sig_allocacmp_i_load + 3'd1);

assign add_ln149_1_fu_390_p2 = (select_ln148_fu_369_p3 + 9'd16);

assign add_ln149_2_fu_315_p2 = (ap_sig_allocacmp_indvar_flatten216_load + 8'd1);

assign add_ln149_fu_248_p2 = (select_ln148_1_fu_202_p3 + 3'd1);

assign add_ln150_fu_309_p2 = (select_ln149_1_fu_260_p3 + 5'd1);

assign add_ln151_1_fu_280_p2 = (tmp_101_cast_fu_222_p3 + zext_ln151_fu_276_p1);

assign add_ln151_2_fu_298_p2 = (tmp_103_cast_fu_286_p3 + zext_ln151_1_fu_294_p1);

assign add_ln151_fu_415_p2 = (select_ln149_fu_396_p3 + 9'd1);

assign and_ln148_fu_242_p2 = (xor_ln148_fu_230_p2 & icmp_ln150_fu_236_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign flattened_output_address0 = index_1_cast_fu_410_p1;

assign flattened_output_d0 = pool2_output_q0;

assign icmp_ln148_fu_166_p2 = ((ap_sig_allocacmp_indvar_flatten232_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_196_p2 = ((ap_sig_allocacmp_indvar_flatten216_load == 8'd64) ? 1'b1 : 1'b0);

assign icmp_ln150_fu_236_p2 = ((ap_sig_allocacmp_d_load == 5'd16) ? 1'b1 : 1'b0);

assign index_1_cast_fu_410_p1 = select_ln149_fu_396_p3;

assign or_ln149_fu_254_p2 = (icmp_ln149_fu_196_p2 | and_ln148_fu_242_p2);

assign pool2_output_address0 = zext_ln151_2_fu_304_p1;

assign select_ln148_1_fu_202_p3 = ((icmp_ln149_fu_196_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_load);

assign select_ln148_2_fu_376_p3 = ((icmp_ln149_reg_495[0:0] == 1'b1) ? add_ln148_1_fu_363_p2 : index_1_fu_68);

assign select_ln148_3_fu_210_p3 = ((icmp_ln149_fu_196_p2[0:0] == 1'b1) ? add_ln148_fu_190_p2 : ap_sig_allocacmp_i_load);

assign select_ln148_4_fu_383_p3 = ((icmp_ln149_reg_495[0:0] == 1'b1) ? add_ln148_1_fu_363_p2 : indvars_iv308_fu_88);

assign select_ln148_fu_369_p3 = ((icmp_ln149_reg_495[0:0] == 1'b1) ? add_ln148_1_fu_363_p2 : index_fu_76);

assign select_ln149_1_fu_260_p3 = ((or_ln149_fu_254_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_d_load);

assign select_ln149_2_fu_268_p3 = ((and_ln148_fu_242_p2[0:0] == 1'b1) ? add_ln149_fu_248_p2 : select_ln148_1_fu_202_p3);

assign select_ln149_3_fu_403_p3 = ((and_ln148_reg_502[0:0] == 1'b1) ? add_ln149_1_fu_390_p2 : select_ln148_fu_369_p3);

assign select_ln149_4_fu_321_p3 = ((icmp_ln149_fu_196_p2[0:0] == 1'b1) ? 8'd1 : add_ln149_2_fu_315_p2);

assign select_ln149_fu_396_p3 = ((and_ln148_reg_502[0:0] == 1'b1) ? add_ln149_1_fu_390_p2 : select_ln148_2_fu_376_p3);

assign tmp_101_cast_fu_222_p3 = {{trunc_ln151_fu_218_p1}, {2'd0}};

assign tmp_103_cast_fu_286_p3 = {{add_ln151_1_fu_280_p2}, {4'd0}};

assign trunc_ln151_fu_218_p1 = select_ln148_3_fu_210_p3[1:0];

assign xor_ln148_fu_230_p2 = (icmp_ln149_fu_196_p2 ^ 1'd1);

assign zext_ln151_1_fu_294_p1 = select_ln149_1_fu_260_p3;

assign zext_ln151_2_fu_304_p1 = add_ln151_2_fu_298_p2;

assign zext_ln151_fu_276_p1 = select_ln149_2_fu_268_p3;

endmodule //lenet_lenet_Pipeline_VITIS_LOOP_148_1_VITIS_LOOP_149_2_VITIS_LOOP_150_3
