// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module systolic_4x4_systolic_4x4_Pipeline_VITIS_LOOP_58_10_VITIS_LOOP_59_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        localC_V_address0,
        localC_V_ce0,
        localC_V_q0,
        localC_V_1_address0,
        localC_V_1_ce0,
        localC_V_1_q0,
        localC_V_2_address0,
        localC_V_2_ce0,
        localC_V_2_q0,
        localC_V_3_address0,
        localC_V_3_ce0,
        localC_V_3_q0,
        localC_V_4_address0,
        localC_V_4_ce0,
        localC_V_4_q0,
        localC_V_5_address0,
        localC_V_5_ce0,
        localC_V_5_q0,
        localC_V_6_address0,
        localC_V_6_ce0,
        localC_V_6_q0,
        localC_V_7_address0,
        localC_V_7_ce0,
        localC_V_7_q0,
        localC_V_8_address0,
        localC_V_8_ce0,
        localC_V_8_q0,
        localC_V_9_address0,
        localC_V_9_ce0,
        localC_V_9_q0,
        localC_V_10_address0,
        localC_V_10_ce0,
        localC_V_10_q0,
        localC_V_11_address0,
        localC_V_11_ce0,
        localC_V_11_q0,
        localC_V_12_address0,
        localC_V_12_ce0,
        localC_V_12_q0,
        localC_V_13_address0,
        localC_V_13_ce0,
        localC_V_13_q0,
        localC_V_14_address0,
        localC_V_14_ce0,
        localC_V_14_q0,
        localC_V_15_address0,
        localC_V_15_ce0,
        localC_V_15_q0,
        localC_V_16_address0,
        localC_V_16_ce0,
        localC_V_16_q0,
        localC_V_17_address0,
        localC_V_17_ce0,
        localC_V_17_q0,
        localC_V_18_address0,
        localC_V_18_ce0,
        localC_V_18_q0,
        localC_V_19_address0,
        localC_V_19_ce0,
        localC_V_19_q0,
        localC_V_20_address0,
        localC_V_20_ce0,
        localC_V_20_q0,
        localC_V_21_address0,
        localC_V_21_ce0,
        localC_V_21_q0,
        localC_V_22_address0,
        localC_V_22_ce0,
        localC_V_22_q0,
        localC_V_23_address0,
        localC_V_23_ce0,
        localC_V_23_q0,
        localC_V_24_address0,
        localC_V_24_ce0,
        localC_V_24_q0,
        localC_V_25_address0,
        localC_V_25_ce0,
        localC_V_25_q0,
        localC_V_26_address0,
        localC_V_26_ce0,
        localC_V_26_q0,
        localC_V_27_address0,
        localC_V_27_ce0,
        localC_V_27_q0,
        localC_V_28_address0,
        localC_V_28_ce0,
        localC_V_28_q0,
        localC_V_29_address0,
        localC_V_29_ce0,
        localC_V_29_q0,
        localC_V_30_address0,
        localC_V_30_ce0,
        localC_V_30_q0,
        localC_V_31_address0,
        localC_V_31_ce0,
        localC_V_31_q0,
        localC_V_32_address0,
        localC_V_32_ce0,
        localC_V_32_q0,
        localC_V_33_address0,
        localC_V_33_ce0,
        localC_V_33_q0,
        localC_V_34_address0,
        localC_V_34_ce0,
        localC_V_34_q0,
        localC_V_35_address0,
        localC_V_35_ce0,
        localC_V_35_q0,
        localC_V_36_address0,
        localC_V_36_ce0,
        localC_V_36_q0,
        localC_V_37_address0,
        localC_V_37_ce0,
        localC_V_37_q0,
        localC_V_38_address0,
        localC_V_38_ce0,
        localC_V_38_q0,
        localC_V_39_address0,
        localC_V_39_ce0,
        localC_V_39_q0,
        localC_V_40_address0,
        localC_V_40_ce0,
        localC_V_40_q0,
        localC_V_41_address0,
        localC_V_41_ce0,
        localC_V_41_q0,
        localC_V_42_address0,
        localC_V_42_ce0,
        localC_V_42_q0,
        localC_V_43_address0,
        localC_V_43_ce0,
        localC_V_43_q0,
        localC_V_44_address0,
        localC_V_44_ce0,
        localC_V_44_q0,
        localC_V_45_address0,
        localC_V_45_ce0,
        localC_V_45_q0,
        localC_V_46_address0,
        localC_V_46_ce0,
        localC_V_46_q0,
        localC_V_47_address0,
        localC_V_47_ce0,
        localC_V_47_q0,
        localC_V_48_address0,
        localC_V_48_ce0,
        localC_V_48_q0,
        localC_V_49_address0,
        localC_V_49_ce0,
        localC_V_49_q0,
        localC_V_50_address0,
        localC_V_50_ce0,
        localC_V_50_q0,
        localC_V_51_address0,
        localC_V_51_ce0,
        localC_V_51_q0,
        localC_V_52_address0,
        localC_V_52_ce0,
        localC_V_52_q0,
        localC_V_53_address0,
        localC_V_53_ce0,
        localC_V_53_q0,
        localC_V_54_address0,
        localC_V_54_ce0,
        localC_V_54_q0,
        localC_V_55_address0,
        localC_V_55_ce0,
        localC_V_55_q0,
        localC_V_56_address0,
        localC_V_56_ce0,
        localC_V_56_q0,
        localC_V_57_address0,
        localC_V_57_ce0,
        localC_V_57_q0,
        localC_V_58_address0,
        localC_V_58_ce0,
        localC_V_58_q0,
        localC_V_59_address0,
        localC_V_59_ce0,
        localC_V_59_q0,
        localC_V_60_address0,
        localC_V_60_ce0,
        localC_V_60_q0,
        localC_V_61_address0,
        localC_V_61_ce0,
        localC_V_61_q0,
        localC_V_62_address0,
        localC_V_62_ce0,
        localC_V_62_q0,
        localC_V_63_address0,
        localC_V_63_ce0,
        localC_V_63_q0,
        C_mem_Addr_A,
        C_mem_EN_A,
        C_mem_WEN_A,
        C_mem_Din_A,
        C_mem_Dout_A
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] localC_V_address0;
output   localC_V_ce0;
input  [31:0] localC_V_q0;
output  [5:0] localC_V_1_address0;
output   localC_V_1_ce0;
input  [31:0] localC_V_1_q0;
output  [5:0] localC_V_2_address0;
output   localC_V_2_ce0;
input  [31:0] localC_V_2_q0;
output  [5:0] localC_V_3_address0;
output   localC_V_3_ce0;
input  [31:0] localC_V_3_q0;
output  [5:0] localC_V_4_address0;
output   localC_V_4_ce0;
input  [31:0] localC_V_4_q0;
output  [5:0] localC_V_5_address0;
output   localC_V_5_ce0;
input  [31:0] localC_V_5_q0;
output  [5:0] localC_V_6_address0;
output   localC_V_6_ce0;
input  [31:0] localC_V_6_q0;
output  [5:0] localC_V_7_address0;
output   localC_V_7_ce0;
input  [31:0] localC_V_7_q0;
output  [5:0] localC_V_8_address0;
output   localC_V_8_ce0;
input  [31:0] localC_V_8_q0;
output  [5:0] localC_V_9_address0;
output   localC_V_9_ce0;
input  [31:0] localC_V_9_q0;
output  [5:0] localC_V_10_address0;
output   localC_V_10_ce0;
input  [31:0] localC_V_10_q0;
output  [5:0] localC_V_11_address0;
output   localC_V_11_ce0;
input  [31:0] localC_V_11_q0;
output  [5:0] localC_V_12_address0;
output   localC_V_12_ce0;
input  [31:0] localC_V_12_q0;
output  [5:0] localC_V_13_address0;
output   localC_V_13_ce0;
input  [31:0] localC_V_13_q0;
output  [5:0] localC_V_14_address0;
output   localC_V_14_ce0;
input  [31:0] localC_V_14_q0;
output  [5:0] localC_V_15_address0;
output   localC_V_15_ce0;
input  [31:0] localC_V_15_q0;
output  [5:0] localC_V_16_address0;
output   localC_V_16_ce0;
input  [31:0] localC_V_16_q0;
output  [5:0] localC_V_17_address0;
output   localC_V_17_ce0;
input  [31:0] localC_V_17_q0;
output  [5:0] localC_V_18_address0;
output   localC_V_18_ce0;
input  [31:0] localC_V_18_q0;
output  [5:0] localC_V_19_address0;
output   localC_V_19_ce0;
input  [31:0] localC_V_19_q0;
output  [5:0] localC_V_20_address0;
output   localC_V_20_ce0;
input  [31:0] localC_V_20_q0;
output  [5:0] localC_V_21_address0;
output   localC_V_21_ce0;
input  [31:0] localC_V_21_q0;
output  [5:0] localC_V_22_address0;
output   localC_V_22_ce0;
input  [31:0] localC_V_22_q0;
output  [5:0] localC_V_23_address0;
output   localC_V_23_ce0;
input  [31:0] localC_V_23_q0;
output  [5:0] localC_V_24_address0;
output   localC_V_24_ce0;
input  [31:0] localC_V_24_q0;
output  [5:0] localC_V_25_address0;
output   localC_V_25_ce0;
input  [31:0] localC_V_25_q0;
output  [5:0] localC_V_26_address0;
output   localC_V_26_ce0;
input  [31:0] localC_V_26_q0;
output  [5:0] localC_V_27_address0;
output   localC_V_27_ce0;
input  [31:0] localC_V_27_q0;
output  [5:0] localC_V_28_address0;
output   localC_V_28_ce0;
input  [31:0] localC_V_28_q0;
output  [5:0] localC_V_29_address0;
output   localC_V_29_ce0;
input  [31:0] localC_V_29_q0;
output  [5:0] localC_V_30_address0;
output   localC_V_30_ce0;
input  [31:0] localC_V_30_q0;
output  [5:0] localC_V_31_address0;
output   localC_V_31_ce0;
input  [31:0] localC_V_31_q0;
output  [5:0] localC_V_32_address0;
output   localC_V_32_ce0;
input  [31:0] localC_V_32_q0;
output  [5:0] localC_V_33_address0;
output   localC_V_33_ce0;
input  [31:0] localC_V_33_q0;
output  [5:0] localC_V_34_address0;
output   localC_V_34_ce0;
input  [31:0] localC_V_34_q0;
output  [5:0] localC_V_35_address0;
output   localC_V_35_ce0;
input  [31:0] localC_V_35_q0;
output  [5:0] localC_V_36_address0;
output   localC_V_36_ce0;
input  [31:0] localC_V_36_q0;
output  [5:0] localC_V_37_address0;
output   localC_V_37_ce0;
input  [31:0] localC_V_37_q0;
output  [5:0] localC_V_38_address0;
output   localC_V_38_ce0;
input  [31:0] localC_V_38_q0;
output  [5:0] localC_V_39_address0;
output   localC_V_39_ce0;
input  [31:0] localC_V_39_q0;
output  [5:0] localC_V_40_address0;
output   localC_V_40_ce0;
input  [31:0] localC_V_40_q0;
output  [5:0] localC_V_41_address0;
output   localC_V_41_ce0;
input  [31:0] localC_V_41_q0;
output  [5:0] localC_V_42_address0;
output   localC_V_42_ce0;
input  [31:0] localC_V_42_q0;
output  [5:0] localC_V_43_address0;
output   localC_V_43_ce0;
input  [31:0] localC_V_43_q0;
output  [5:0] localC_V_44_address0;
output   localC_V_44_ce0;
input  [31:0] localC_V_44_q0;
output  [5:0] localC_V_45_address0;
output   localC_V_45_ce0;
input  [31:0] localC_V_45_q0;
output  [5:0] localC_V_46_address0;
output   localC_V_46_ce0;
input  [31:0] localC_V_46_q0;
output  [5:0] localC_V_47_address0;
output   localC_V_47_ce0;
input  [31:0] localC_V_47_q0;
output  [5:0] localC_V_48_address0;
output   localC_V_48_ce0;
input  [31:0] localC_V_48_q0;
output  [5:0] localC_V_49_address0;
output   localC_V_49_ce0;
input  [31:0] localC_V_49_q0;
output  [5:0] localC_V_50_address0;
output   localC_V_50_ce0;
input  [31:0] localC_V_50_q0;
output  [5:0] localC_V_51_address0;
output   localC_V_51_ce0;
input  [31:0] localC_V_51_q0;
output  [5:0] localC_V_52_address0;
output   localC_V_52_ce0;
input  [31:0] localC_V_52_q0;
output  [5:0] localC_V_53_address0;
output   localC_V_53_ce0;
input  [31:0] localC_V_53_q0;
output  [5:0] localC_V_54_address0;
output   localC_V_54_ce0;
input  [31:0] localC_V_54_q0;
output  [5:0] localC_V_55_address0;
output   localC_V_55_ce0;
input  [31:0] localC_V_55_q0;
output  [5:0] localC_V_56_address0;
output   localC_V_56_ce0;
input  [31:0] localC_V_56_q0;
output  [5:0] localC_V_57_address0;
output   localC_V_57_ce0;
input  [31:0] localC_V_57_q0;
output  [5:0] localC_V_58_address0;
output   localC_V_58_ce0;
input  [31:0] localC_V_58_q0;
output  [5:0] localC_V_59_address0;
output   localC_V_59_ce0;
input  [31:0] localC_V_59_q0;
output  [5:0] localC_V_60_address0;
output   localC_V_60_ce0;
input  [31:0] localC_V_60_q0;
output  [5:0] localC_V_61_address0;
output   localC_V_61_ce0;
input  [31:0] localC_V_61_q0;
output  [5:0] localC_V_62_address0;
output   localC_V_62_ce0;
input  [31:0] localC_V_62_q0;
output  [5:0] localC_V_63_address0;
output   localC_V_63_ce0;
input  [31:0] localC_V_63_q0;
output  [31:0] C_mem_Addr_A;
output   C_mem_EN_A;
output  [3:0] C_mem_WEN_A;
output  [31:0] C_mem_Din_A;
input  [31:0] C_mem_Dout_A;

reg ap_idle;
reg localC_V_ce0;
reg localC_V_1_ce0;
reg localC_V_2_ce0;
reg localC_V_3_ce0;
reg localC_V_4_ce0;
reg localC_V_5_ce0;
reg localC_V_6_ce0;
reg localC_V_7_ce0;
reg localC_V_8_ce0;
reg localC_V_9_ce0;
reg localC_V_10_ce0;
reg localC_V_11_ce0;
reg localC_V_12_ce0;
reg localC_V_13_ce0;
reg localC_V_14_ce0;
reg localC_V_15_ce0;
reg localC_V_16_ce0;
reg localC_V_17_ce0;
reg localC_V_18_ce0;
reg localC_V_19_ce0;
reg localC_V_20_ce0;
reg localC_V_21_ce0;
reg localC_V_22_ce0;
reg localC_V_23_ce0;
reg localC_V_24_ce0;
reg localC_V_25_ce0;
reg localC_V_26_ce0;
reg localC_V_27_ce0;
reg localC_V_28_ce0;
reg localC_V_29_ce0;
reg localC_V_30_ce0;
reg localC_V_31_ce0;
reg localC_V_32_ce0;
reg localC_V_33_ce0;
reg localC_V_34_ce0;
reg localC_V_35_ce0;
reg localC_V_36_ce0;
reg localC_V_37_ce0;
reg localC_V_38_ce0;
reg localC_V_39_ce0;
reg localC_V_40_ce0;
reg localC_V_41_ce0;
reg localC_V_42_ce0;
reg localC_V_43_ce0;
reg localC_V_44_ce0;
reg localC_V_45_ce0;
reg localC_V_46_ce0;
reg localC_V_47_ce0;
reg localC_V_48_ce0;
reg localC_V_49_ce0;
reg localC_V_50_ce0;
reg localC_V_51_ce0;
reg localC_V_52_ce0;
reg localC_V_53_ce0;
reg localC_V_54_ce0;
reg localC_V_55_ce0;
reg localC_V_56_ce0;
reg localC_V_57_ce0;
reg localC_V_58_ce0;
reg localC_V_59_ce0;
reg localC_V_60_ce0;
reg localC_V_61_ce0;
reg localC_V_62_ce0;
reg localC_V_63_ce0;
reg C_mem_EN_A;
reg[3:0] C_mem_WEN_A;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln58_fu_1049_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] select_ln58_fu_1073_p3;
reg   [6:0] select_ln58_reg_1383;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] trunc_ln58_fu_1095_p1;
reg   [5:0] trunc_ln58_reg_1389;
wire   [63:0] zext_ln58_fu_1115_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln61_fu_1220_p1;
reg   [6:0] j_fu_174;
wire   [6:0] add_ln59_fu_1183_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_178;
wire   [6:0] select_ln58_1_fu_1087_p3;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [12:0] indvar_flatten357_fu_182;
wire   [12:0] add_ln58_fu_1055_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten357_load;
wire   [31:0] tmp_1_fu_1225_p66;
wire   [31:0] C_mem_Addr_A_orig;
wire   [0:0] icmp_ln59_fu_1067_p2;
wire   [6:0] add_ln58_1_fu_1081_p2;
wire   [5:0] trunc_ln58_1_fu_1099_p1;
wire   [5:0] trunc_ln58_2_fu_1103_p1;
wire   [5:0] select_ln58_3_fu_1107_p3;
wire   [11:0] zext_ln59_fu_1211_p1;
wire   [11:0] p_mid1_fu_1204_p3;
wire   [11:0] add_ln18_fu_1214_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

systolic_4x4_mux_647_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mux_647_32_1_1_U452(
    .din0(localC_V_q0),
    .din1(localC_V_1_q0),
    .din2(localC_V_2_q0),
    .din3(localC_V_3_q0),
    .din4(localC_V_4_q0),
    .din5(localC_V_5_q0),
    .din6(localC_V_6_q0),
    .din7(localC_V_7_q0),
    .din8(localC_V_8_q0),
    .din9(localC_V_9_q0),
    .din10(localC_V_10_q0),
    .din11(localC_V_11_q0),
    .din12(localC_V_12_q0),
    .din13(localC_V_13_q0),
    .din14(localC_V_14_q0),
    .din15(localC_V_15_q0),
    .din16(localC_V_16_q0),
    .din17(localC_V_17_q0),
    .din18(localC_V_18_q0),
    .din19(localC_V_19_q0),
    .din20(localC_V_20_q0),
    .din21(localC_V_21_q0),
    .din22(localC_V_22_q0),
    .din23(localC_V_23_q0),
    .din24(localC_V_24_q0),
    .din25(localC_V_25_q0),
    .din26(localC_V_26_q0),
    .din27(localC_V_27_q0),
    .din28(localC_V_28_q0),
    .din29(localC_V_29_q0),
    .din30(localC_V_30_q0),
    .din31(localC_V_31_q0),
    .din32(localC_V_32_q0),
    .din33(localC_V_33_q0),
    .din34(localC_V_34_q0),
    .din35(localC_V_35_q0),
    .din36(localC_V_36_q0),
    .din37(localC_V_37_q0),
    .din38(localC_V_38_q0),
    .din39(localC_V_39_q0),
    .din40(localC_V_40_q0),
    .din41(localC_V_41_q0),
    .din42(localC_V_42_q0),
    .din43(localC_V_43_q0),
    .din44(localC_V_44_q0),
    .din45(localC_V_45_q0),
    .din46(localC_V_46_q0),
    .din47(localC_V_47_q0),
    .din48(localC_V_48_q0),
    .din49(localC_V_49_q0),
    .din50(localC_V_50_q0),
    .din51(localC_V_51_q0),
    .din52(localC_V_52_q0),
    .din53(localC_V_53_q0),
    .din54(localC_V_54_q0),
    .din55(localC_V_55_q0),
    .din56(localC_V_56_q0),
    .din57(localC_V_57_q0),
    .din58(localC_V_58_q0),
    .din59(localC_V_59_q0),
    .din60(localC_V_60_q0),
    .din61(localC_V_61_q0),
    .din62(localC_V_62_q0),
    .din63(localC_V_63_q0),
    .din64(select_ln58_reg_1383),
    .dout(tmp_1_fu_1225_p66)
);

systolic_4x4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln58_fu_1049_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_178 <= select_ln58_1_fu_1087_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_178 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln58_fu_1049_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten357_fu_182 <= add_ln58_fu_1055_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten357_fu_182 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln58_fu_1049_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_174 <= add_ln59_fu_1183_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_174 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_1049_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln58_reg_1383 <= select_ln58_fu_1073_p3;
        trunc_ln58_reg_1389 <= trunc_ln58_fu_1095_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_mem_EN_A = 1'b1;
    end else begin
        C_mem_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_mem_WEN_A = 4'd15;
    end else begin
        C_mem_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((icmp_ln58_fu_1049_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_178;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten357_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten357_load = indvar_flatten357_fu_182;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_10_ce0 = 1'b1;
    end else begin
        localC_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_11_ce0 = 1'b1;
    end else begin
        localC_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_12_ce0 = 1'b1;
    end else begin
        localC_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_13_ce0 = 1'b1;
    end else begin
        localC_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_14_ce0 = 1'b1;
    end else begin
        localC_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_15_ce0 = 1'b1;
    end else begin
        localC_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_16_ce0 = 1'b1;
    end else begin
        localC_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_17_ce0 = 1'b1;
    end else begin
        localC_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_18_ce0 = 1'b1;
    end else begin
        localC_V_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_19_ce0 = 1'b1;
    end else begin
        localC_V_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_1_ce0 = 1'b1;
    end else begin
        localC_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_20_ce0 = 1'b1;
    end else begin
        localC_V_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_21_ce0 = 1'b1;
    end else begin
        localC_V_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_22_ce0 = 1'b1;
    end else begin
        localC_V_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_23_ce0 = 1'b1;
    end else begin
        localC_V_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_24_ce0 = 1'b1;
    end else begin
        localC_V_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_25_ce0 = 1'b1;
    end else begin
        localC_V_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_26_ce0 = 1'b1;
    end else begin
        localC_V_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_27_ce0 = 1'b1;
    end else begin
        localC_V_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_28_ce0 = 1'b1;
    end else begin
        localC_V_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_29_ce0 = 1'b1;
    end else begin
        localC_V_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_2_ce0 = 1'b1;
    end else begin
        localC_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_30_ce0 = 1'b1;
    end else begin
        localC_V_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_31_ce0 = 1'b1;
    end else begin
        localC_V_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_32_ce0 = 1'b1;
    end else begin
        localC_V_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_33_ce0 = 1'b1;
    end else begin
        localC_V_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_34_ce0 = 1'b1;
    end else begin
        localC_V_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_35_ce0 = 1'b1;
    end else begin
        localC_V_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_36_ce0 = 1'b1;
    end else begin
        localC_V_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_37_ce0 = 1'b1;
    end else begin
        localC_V_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_38_ce0 = 1'b1;
    end else begin
        localC_V_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_39_ce0 = 1'b1;
    end else begin
        localC_V_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_3_ce0 = 1'b1;
    end else begin
        localC_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_40_ce0 = 1'b1;
    end else begin
        localC_V_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_41_ce0 = 1'b1;
    end else begin
        localC_V_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_42_ce0 = 1'b1;
    end else begin
        localC_V_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_43_ce0 = 1'b1;
    end else begin
        localC_V_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_44_ce0 = 1'b1;
    end else begin
        localC_V_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_45_ce0 = 1'b1;
    end else begin
        localC_V_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_46_ce0 = 1'b1;
    end else begin
        localC_V_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_47_ce0 = 1'b1;
    end else begin
        localC_V_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_48_ce0 = 1'b1;
    end else begin
        localC_V_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_49_ce0 = 1'b1;
    end else begin
        localC_V_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_4_ce0 = 1'b1;
    end else begin
        localC_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_50_ce0 = 1'b1;
    end else begin
        localC_V_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_51_ce0 = 1'b1;
    end else begin
        localC_V_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_52_ce0 = 1'b1;
    end else begin
        localC_V_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_53_ce0 = 1'b1;
    end else begin
        localC_V_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_54_ce0 = 1'b1;
    end else begin
        localC_V_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_55_ce0 = 1'b1;
    end else begin
        localC_V_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_56_ce0 = 1'b1;
    end else begin
        localC_V_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_57_ce0 = 1'b1;
    end else begin
        localC_V_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_58_ce0 = 1'b1;
    end else begin
        localC_V_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_59_ce0 = 1'b1;
    end else begin
        localC_V_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_5_ce0 = 1'b1;
    end else begin
        localC_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_60_ce0 = 1'b1;
    end else begin
        localC_V_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_61_ce0 = 1'b1;
    end else begin
        localC_V_61_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_62_ce0 = 1'b1;
    end else begin
        localC_V_62_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_63_ce0 = 1'b1;
    end else begin
        localC_V_63_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_6_ce0 = 1'b1;
    end else begin
        localC_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_7_ce0 = 1'b1;
    end else begin
        localC_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_8_ce0 = 1'b1;
    end else begin
        localC_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_9_ce0 = 1'b1;
    end else begin
        localC_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localC_V_ce0 = 1'b1;
    end else begin
        localC_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_mem_Addr_A = C_mem_Addr_A_orig << 32'd2;

assign C_mem_Addr_A_orig = zext_ln61_fu_1220_p1;

assign C_mem_Din_A = tmp_1_fu_1225_p66;

assign add_ln18_fu_1214_p2 = (zext_ln59_fu_1211_p1 + p_mid1_fu_1204_p3);

assign add_ln58_1_fu_1081_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign add_ln58_fu_1055_p2 = (ap_sig_allocacmp_indvar_flatten357_load + 13'd1);

assign add_ln59_fu_1183_p2 = (select_ln58_fu_1073_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln58_fu_1049_p2 = ((ap_sig_allocacmp_indvar_flatten357_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_1067_p2 = ((ap_sig_allocacmp_j_load == 7'd64) ? 1'b1 : 1'b0);

assign localC_V_10_address0 = zext_ln58_fu_1115_p1;

assign localC_V_11_address0 = zext_ln58_fu_1115_p1;

assign localC_V_12_address0 = zext_ln58_fu_1115_p1;

assign localC_V_13_address0 = zext_ln58_fu_1115_p1;

assign localC_V_14_address0 = zext_ln58_fu_1115_p1;

assign localC_V_15_address0 = zext_ln58_fu_1115_p1;

assign localC_V_16_address0 = zext_ln58_fu_1115_p1;

assign localC_V_17_address0 = zext_ln58_fu_1115_p1;

assign localC_V_18_address0 = zext_ln58_fu_1115_p1;

assign localC_V_19_address0 = zext_ln58_fu_1115_p1;

assign localC_V_1_address0 = zext_ln58_fu_1115_p1;

assign localC_V_20_address0 = zext_ln58_fu_1115_p1;

assign localC_V_21_address0 = zext_ln58_fu_1115_p1;

assign localC_V_22_address0 = zext_ln58_fu_1115_p1;

assign localC_V_23_address0 = zext_ln58_fu_1115_p1;

assign localC_V_24_address0 = zext_ln58_fu_1115_p1;

assign localC_V_25_address0 = zext_ln58_fu_1115_p1;

assign localC_V_26_address0 = zext_ln58_fu_1115_p1;

assign localC_V_27_address0 = zext_ln58_fu_1115_p1;

assign localC_V_28_address0 = zext_ln58_fu_1115_p1;

assign localC_V_29_address0 = zext_ln58_fu_1115_p1;

assign localC_V_2_address0 = zext_ln58_fu_1115_p1;

assign localC_V_30_address0 = zext_ln58_fu_1115_p1;

assign localC_V_31_address0 = zext_ln58_fu_1115_p1;

assign localC_V_32_address0 = zext_ln58_fu_1115_p1;

assign localC_V_33_address0 = zext_ln58_fu_1115_p1;

assign localC_V_34_address0 = zext_ln58_fu_1115_p1;

assign localC_V_35_address0 = zext_ln58_fu_1115_p1;

assign localC_V_36_address0 = zext_ln58_fu_1115_p1;

assign localC_V_37_address0 = zext_ln58_fu_1115_p1;

assign localC_V_38_address0 = zext_ln58_fu_1115_p1;

assign localC_V_39_address0 = zext_ln58_fu_1115_p1;

assign localC_V_3_address0 = zext_ln58_fu_1115_p1;

assign localC_V_40_address0 = zext_ln58_fu_1115_p1;

assign localC_V_41_address0 = zext_ln58_fu_1115_p1;

assign localC_V_42_address0 = zext_ln58_fu_1115_p1;

assign localC_V_43_address0 = zext_ln58_fu_1115_p1;

assign localC_V_44_address0 = zext_ln58_fu_1115_p1;

assign localC_V_45_address0 = zext_ln58_fu_1115_p1;

assign localC_V_46_address0 = zext_ln58_fu_1115_p1;

assign localC_V_47_address0 = zext_ln58_fu_1115_p1;

assign localC_V_48_address0 = zext_ln58_fu_1115_p1;

assign localC_V_49_address0 = zext_ln58_fu_1115_p1;

assign localC_V_4_address0 = zext_ln58_fu_1115_p1;

assign localC_V_50_address0 = zext_ln58_fu_1115_p1;

assign localC_V_51_address0 = zext_ln58_fu_1115_p1;

assign localC_V_52_address0 = zext_ln58_fu_1115_p1;

assign localC_V_53_address0 = zext_ln58_fu_1115_p1;

assign localC_V_54_address0 = zext_ln58_fu_1115_p1;

assign localC_V_55_address0 = zext_ln58_fu_1115_p1;

assign localC_V_56_address0 = zext_ln58_fu_1115_p1;

assign localC_V_57_address0 = zext_ln58_fu_1115_p1;

assign localC_V_58_address0 = zext_ln58_fu_1115_p1;

assign localC_V_59_address0 = zext_ln58_fu_1115_p1;

assign localC_V_5_address0 = zext_ln58_fu_1115_p1;

assign localC_V_60_address0 = zext_ln58_fu_1115_p1;

assign localC_V_61_address0 = zext_ln58_fu_1115_p1;

assign localC_V_62_address0 = zext_ln58_fu_1115_p1;

assign localC_V_63_address0 = zext_ln58_fu_1115_p1;

assign localC_V_6_address0 = zext_ln58_fu_1115_p1;

assign localC_V_7_address0 = zext_ln58_fu_1115_p1;

assign localC_V_8_address0 = zext_ln58_fu_1115_p1;

assign localC_V_9_address0 = zext_ln58_fu_1115_p1;

assign localC_V_address0 = zext_ln58_fu_1115_p1;

assign p_mid1_fu_1204_p3 = {{trunc_ln58_reg_1389}, {6'd0}};

assign select_ln58_1_fu_1087_p3 = ((icmp_ln59_fu_1067_p2[0:0] == 1'b1) ? add_ln58_1_fu_1081_p2 : ap_sig_allocacmp_i_load);

assign select_ln58_3_fu_1107_p3 = ((icmp_ln59_fu_1067_p2[0:0] == 1'b1) ? trunc_ln58_1_fu_1099_p1 : trunc_ln58_2_fu_1103_p1);

assign select_ln58_fu_1073_p3 = ((icmp_ln59_fu_1067_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign trunc_ln58_1_fu_1099_p1 = add_ln58_1_fu_1081_p2[5:0];

assign trunc_ln58_2_fu_1103_p1 = ap_sig_allocacmp_i_load[5:0];

assign trunc_ln58_fu_1095_p1 = select_ln58_1_fu_1087_p3[5:0];

assign zext_ln58_fu_1115_p1 = select_ln58_3_fu_1107_p3;

assign zext_ln59_fu_1211_p1 = select_ln58_reg_1383;

assign zext_ln61_fu_1220_p1 = add_ln18_fu_1214_p2;

endmodule //systolic_4x4_systolic_4x4_Pipeline_VITIS_LOOP_58_10_VITIS_LOOP_59_11
