// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module systolic_4x4_systolic_4x4_Pipeline_VITIS_LOOP_39_5_VITIS_LOOP_40_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        localC_V_address0,
        localC_V_ce0,
        localC_V_we0,
        localC_V_d0,
        localC_V_1_address0,
        localC_V_1_ce0,
        localC_V_1_we0,
        localC_V_1_d0,
        localC_V_2_address0,
        localC_V_2_ce0,
        localC_V_2_we0,
        localC_V_2_d0,
        localC_V_3_address0,
        localC_V_3_ce0,
        localC_V_3_we0,
        localC_V_3_d0,
        localC_V_4_address0,
        localC_V_4_ce0,
        localC_V_4_we0,
        localC_V_4_d0,
        localC_V_5_address0,
        localC_V_5_ce0,
        localC_V_5_we0,
        localC_V_5_d0,
        localC_V_6_address0,
        localC_V_6_ce0,
        localC_V_6_we0,
        localC_V_6_d0,
        localC_V_7_address0,
        localC_V_7_ce0,
        localC_V_7_we0,
        localC_V_7_d0,
        localC_V_8_address0,
        localC_V_8_ce0,
        localC_V_8_we0,
        localC_V_8_d0,
        localC_V_9_address0,
        localC_V_9_ce0,
        localC_V_9_we0,
        localC_V_9_d0,
        localC_V_10_address0,
        localC_V_10_ce0,
        localC_V_10_we0,
        localC_V_10_d0,
        localC_V_11_address0,
        localC_V_11_ce0,
        localC_V_11_we0,
        localC_V_11_d0,
        localC_V_12_address0,
        localC_V_12_ce0,
        localC_V_12_we0,
        localC_V_12_d0,
        localC_V_13_address0,
        localC_V_13_ce0,
        localC_V_13_we0,
        localC_V_13_d0,
        localC_V_14_address0,
        localC_V_14_ce0,
        localC_V_14_we0,
        localC_V_14_d0,
        localC_V_15_address0,
        localC_V_15_ce0,
        localC_V_15_we0,
        localC_V_15_d0,
        localC_V_16_address0,
        localC_V_16_ce0,
        localC_V_16_we0,
        localC_V_16_d0,
        localC_V_17_address0,
        localC_V_17_ce0,
        localC_V_17_we0,
        localC_V_17_d0,
        localC_V_18_address0,
        localC_V_18_ce0,
        localC_V_18_we0,
        localC_V_18_d0,
        localC_V_19_address0,
        localC_V_19_ce0,
        localC_V_19_we0,
        localC_V_19_d0,
        localC_V_20_address0,
        localC_V_20_ce0,
        localC_V_20_we0,
        localC_V_20_d0,
        localC_V_21_address0,
        localC_V_21_ce0,
        localC_V_21_we0,
        localC_V_21_d0,
        localC_V_22_address0,
        localC_V_22_ce0,
        localC_V_22_we0,
        localC_V_22_d0,
        localC_V_23_address0,
        localC_V_23_ce0,
        localC_V_23_we0,
        localC_V_23_d0,
        localC_V_24_address0,
        localC_V_24_ce0,
        localC_V_24_we0,
        localC_V_24_d0,
        localC_V_25_address0,
        localC_V_25_ce0,
        localC_V_25_we0,
        localC_V_25_d0,
        localC_V_26_address0,
        localC_V_26_ce0,
        localC_V_26_we0,
        localC_V_26_d0,
        localC_V_27_address0,
        localC_V_27_ce0,
        localC_V_27_we0,
        localC_V_27_d0,
        localC_V_28_address0,
        localC_V_28_ce0,
        localC_V_28_we0,
        localC_V_28_d0,
        localC_V_29_address0,
        localC_V_29_ce0,
        localC_V_29_we0,
        localC_V_29_d0,
        localC_V_30_address0,
        localC_V_30_ce0,
        localC_V_30_we0,
        localC_V_30_d0,
        localC_V_31_address0,
        localC_V_31_ce0,
        localC_V_31_we0,
        localC_V_31_d0,
        localC_V_32_address0,
        localC_V_32_ce0,
        localC_V_32_we0,
        localC_V_32_d0,
        localC_V_33_address0,
        localC_V_33_ce0,
        localC_V_33_we0,
        localC_V_33_d0,
        localC_V_34_address0,
        localC_V_34_ce0,
        localC_V_34_we0,
        localC_V_34_d0,
        localC_V_35_address0,
        localC_V_35_ce0,
        localC_V_35_we0,
        localC_V_35_d0,
        localC_V_36_address0,
        localC_V_36_ce0,
        localC_V_36_we0,
        localC_V_36_d0,
        localC_V_37_address0,
        localC_V_37_ce0,
        localC_V_37_we0,
        localC_V_37_d0,
        localC_V_38_address0,
        localC_V_38_ce0,
        localC_V_38_we0,
        localC_V_38_d0,
        localC_V_39_address0,
        localC_V_39_ce0,
        localC_V_39_we0,
        localC_V_39_d0,
        localC_V_40_address0,
        localC_V_40_ce0,
        localC_V_40_we0,
        localC_V_40_d0,
        localC_V_41_address0,
        localC_V_41_ce0,
        localC_V_41_we0,
        localC_V_41_d0,
        localC_V_42_address0,
        localC_V_42_ce0,
        localC_V_42_we0,
        localC_V_42_d0,
        localC_V_43_address0,
        localC_V_43_ce0,
        localC_V_43_we0,
        localC_V_43_d0,
        localC_V_44_address0,
        localC_V_44_ce0,
        localC_V_44_we0,
        localC_V_44_d0,
        localC_V_45_address0,
        localC_V_45_ce0,
        localC_V_45_we0,
        localC_V_45_d0,
        localC_V_46_address0,
        localC_V_46_ce0,
        localC_V_46_we0,
        localC_V_46_d0,
        localC_V_47_address0,
        localC_V_47_ce0,
        localC_V_47_we0,
        localC_V_47_d0,
        localC_V_48_address0,
        localC_V_48_ce0,
        localC_V_48_we0,
        localC_V_48_d0,
        localC_V_49_address0,
        localC_V_49_ce0,
        localC_V_49_we0,
        localC_V_49_d0,
        localC_V_50_address0,
        localC_V_50_ce0,
        localC_V_50_we0,
        localC_V_50_d0,
        localC_V_51_address0,
        localC_V_51_ce0,
        localC_V_51_we0,
        localC_V_51_d0,
        localC_V_52_address0,
        localC_V_52_ce0,
        localC_V_52_we0,
        localC_V_52_d0,
        localC_V_53_address0,
        localC_V_53_ce0,
        localC_V_53_we0,
        localC_V_53_d0,
        localC_V_54_address0,
        localC_V_54_ce0,
        localC_V_54_we0,
        localC_V_54_d0,
        localC_V_55_address0,
        localC_V_55_ce0,
        localC_V_55_we0,
        localC_V_55_d0,
        localC_V_56_address0,
        localC_V_56_ce0,
        localC_V_56_we0,
        localC_V_56_d0,
        localC_V_57_address0,
        localC_V_57_ce0,
        localC_V_57_we0,
        localC_V_57_d0,
        localC_V_58_address0,
        localC_V_58_ce0,
        localC_V_58_we0,
        localC_V_58_d0,
        localC_V_59_address0,
        localC_V_59_ce0,
        localC_V_59_we0,
        localC_V_59_d0,
        localC_V_60_address0,
        localC_V_60_ce0,
        localC_V_60_we0,
        localC_V_60_d0,
        localC_V_61_address0,
        localC_V_61_ce0,
        localC_V_61_we0,
        localC_V_61_d0,
        localC_V_62_address0,
        localC_V_62_ce0,
        localC_V_62_we0,
        localC_V_62_d0,
        localC_V_63_address0,
        localC_V_63_ce0,
        localC_V_63_we0,
        localC_V_63_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] localC_V_address0;
output   localC_V_ce0;
output   localC_V_we0;
output  [31:0] localC_V_d0;
output  [5:0] localC_V_1_address0;
output   localC_V_1_ce0;
output   localC_V_1_we0;
output  [31:0] localC_V_1_d0;
output  [5:0] localC_V_2_address0;
output   localC_V_2_ce0;
output   localC_V_2_we0;
output  [31:0] localC_V_2_d0;
output  [5:0] localC_V_3_address0;
output   localC_V_3_ce0;
output   localC_V_3_we0;
output  [31:0] localC_V_3_d0;
output  [5:0] localC_V_4_address0;
output   localC_V_4_ce0;
output   localC_V_4_we0;
output  [31:0] localC_V_4_d0;
output  [5:0] localC_V_5_address0;
output   localC_V_5_ce0;
output   localC_V_5_we0;
output  [31:0] localC_V_5_d0;
output  [5:0] localC_V_6_address0;
output   localC_V_6_ce0;
output   localC_V_6_we0;
output  [31:0] localC_V_6_d0;
output  [5:0] localC_V_7_address0;
output   localC_V_7_ce0;
output   localC_V_7_we0;
output  [31:0] localC_V_7_d0;
output  [5:0] localC_V_8_address0;
output   localC_V_8_ce0;
output   localC_V_8_we0;
output  [31:0] localC_V_8_d0;
output  [5:0] localC_V_9_address0;
output   localC_V_9_ce0;
output   localC_V_9_we0;
output  [31:0] localC_V_9_d0;
output  [5:0] localC_V_10_address0;
output   localC_V_10_ce0;
output   localC_V_10_we0;
output  [31:0] localC_V_10_d0;
output  [5:0] localC_V_11_address0;
output   localC_V_11_ce0;
output   localC_V_11_we0;
output  [31:0] localC_V_11_d0;
output  [5:0] localC_V_12_address0;
output   localC_V_12_ce0;
output   localC_V_12_we0;
output  [31:0] localC_V_12_d0;
output  [5:0] localC_V_13_address0;
output   localC_V_13_ce0;
output   localC_V_13_we0;
output  [31:0] localC_V_13_d0;
output  [5:0] localC_V_14_address0;
output   localC_V_14_ce0;
output   localC_V_14_we0;
output  [31:0] localC_V_14_d0;
output  [5:0] localC_V_15_address0;
output   localC_V_15_ce0;
output   localC_V_15_we0;
output  [31:0] localC_V_15_d0;
output  [5:0] localC_V_16_address0;
output   localC_V_16_ce0;
output   localC_V_16_we0;
output  [31:0] localC_V_16_d0;
output  [5:0] localC_V_17_address0;
output   localC_V_17_ce0;
output   localC_V_17_we0;
output  [31:0] localC_V_17_d0;
output  [5:0] localC_V_18_address0;
output   localC_V_18_ce0;
output   localC_V_18_we0;
output  [31:0] localC_V_18_d0;
output  [5:0] localC_V_19_address0;
output   localC_V_19_ce0;
output   localC_V_19_we0;
output  [31:0] localC_V_19_d0;
output  [5:0] localC_V_20_address0;
output   localC_V_20_ce0;
output   localC_V_20_we0;
output  [31:0] localC_V_20_d0;
output  [5:0] localC_V_21_address0;
output   localC_V_21_ce0;
output   localC_V_21_we0;
output  [31:0] localC_V_21_d0;
output  [5:0] localC_V_22_address0;
output   localC_V_22_ce0;
output   localC_V_22_we0;
output  [31:0] localC_V_22_d0;
output  [5:0] localC_V_23_address0;
output   localC_V_23_ce0;
output   localC_V_23_we0;
output  [31:0] localC_V_23_d0;
output  [5:0] localC_V_24_address0;
output   localC_V_24_ce0;
output   localC_V_24_we0;
output  [31:0] localC_V_24_d0;
output  [5:0] localC_V_25_address0;
output   localC_V_25_ce0;
output   localC_V_25_we0;
output  [31:0] localC_V_25_d0;
output  [5:0] localC_V_26_address0;
output   localC_V_26_ce0;
output   localC_V_26_we0;
output  [31:0] localC_V_26_d0;
output  [5:0] localC_V_27_address0;
output   localC_V_27_ce0;
output   localC_V_27_we0;
output  [31:0] localC_V_27_d0;
output  [5:0] localC_V_28_address0;
output   localC_V_28_ce0;
output   localC_V_28_we0;
output  [31:0] localC_V_28_d0;
output  [5:0] localC_V_29_address0;
output   localC_V_29_ce0;
output   localC_V_29_we0;
output  [31:0] localC_V_29_d0;
output  [5:0] localC_V_30_address0;
output   localC_V_30_ce0;
output   localC_V_30_we0;
output  [31:0] localC_V_30_d0;
output  [5:0] localC_V_31_address0;
output   localC_V_31_ce0;
output   localC_V_31_we0;
output  [31:0] localC_V_31_d0;
output  [5:0] localC_V_32_address0;
output   localC_V_32_ce0;
output   localC_V_32_we0;
output  [31:0] localC_V_32_d0;
output  [5:0] localC_V_33_address0;
output   localC_V_33_ce0;
output   localC_V_33_we0;
output  [31:0] localC_V_33_d0;
output  [5:0] localC_V_34_address0;
output   localC_V_34_ce0;
output   localC_V_34_we0;
output  [31:0] localC_V_34_d0;
output  [5:0] localC_V_35_address0;
output   localC_V_35_ce0;
output   localC_V_35_we0;
output  [31:0] localC_V_35_d0;
output  [5:0] localC_V_36_address0;
output   localC_V_36_ce0;
output   localC_V_36_we0;
output  [31:0] localC_V_36_d0;
output  [5:0] localC_V_37_address0;
output   localC_V_37_ce0;
output   localC_V_37_we0;
output  [31:0] localC_V_37_d0;
output  [5:0] localC_V_38_address0;
output   localC_V_38_ce0;
output   localC_V_38_we0;
output  [31:0] localC_V_38_d0;
output  [5:0] localC_V_39_address0;
output   localC_V_39_ce0;
output   localC_V_39_we0;
output  [31:0] localC_V_39_d0;
output  [5:0] localC_V_40_address0;
output   localC_V_40_ce0;
output   localC_V_40_we0;
output  [31:0] localC_V_40_d0;
output  [5:0] localC_V_41_address0;
output   localC_V_41_ce0;
output   localC_V_41_we0;
output  [31:0] localC_V_41_d0;
output  [5:0] localC_V_42_address0;
output   localC_V_42_ce0;
output   localC_V_42_we0;
output  [31:0] localC_V_42_d0;
output  [5:0] localC_V_43_address0;
output   localC_V_43_ce0;
output   localC_V_43_we0;
output  [31:0] localC_V_43_d0;
output  [5:0] localC_V_44_address0;
output   localC_V_44_ce0;
output   localC_V_44_we0;
output  [31:0] localC_V_44_d0;
output  [5:0] localC_V_45_address0;
output   localC_V_45_ce0;
output   localC_V_45_we0;
output  [31:0] localC_V_45_d0;
output  [5:0] localC_V_46_address0;
output   localC_V_46_ce0;
output   localC_V_46_we0;
output  [31:0] localC_V_46_d0;
output  [5:0] localC_V_47_address0;
output   localC_V_47_ce0;
output   localC_V_47_we0;
output  [31:0] localC_V_47_d0;
output  [5:0] localC_V_48_address0;
output   localC_V_48_ce0;
output   localC_V_48_we0;
output  [31:0] localC_V_48_d0;
output  [5:0] localC_V_49_address0;
output   localC_V_49_ce0;
output   localC_V_49_we0;
output  [31:0] localC_V_49_d0;
output  [5:0] localC_V_50_address0;
output   localC_V_50_ce0;
output   localC_V_50_we0;
output  [31:0] localC_V_50_d0;
output  [5:0] localC_V_51_address0;
output   localC_V_51_ce0;
output   localC_V_51_we0;
output  [31:0] localC_V_51_d0;
output  [5:0] localC_V_52_address0;
output   localC_V_52_ce0;
output   localC_V_52_we0;
output  [31:0] localC_V_52_d0;
output  [5:0] localC_V_53_address0;
output   localC_V_53_ce0;
output   localC_V_53_we0;
output  [31:0] localC_V_53_d0;
output  [5:0] localC_V_54_address0;
output   localC_V_54_ce0;
output   localC_V_54_we0;
output  [31:0] localC_V_54_d0;
output  [5:0] localC_V_55_address0;
output   localC_V_55_ce0;
output   localC_V_55_we0;
output  [31:0] localC_V_55_d0;
output  [5:0] localC_V_56_address0;
output   localC_V_56_ce0;
output   localC_V_56_we0;
output  [31:0] localC_V_56_d0;
output  [5:0] localC_V_57_address0;
output   localC_V_57_ce0;
output   localC_V_57_we0;
output  [31:0] localC_V_57_d0;
output  [5:0] localC_V_58_address0;
output   localC_V_58_ce0;
output   localC_V_58_we0;
output  [31:0] localC_V_58_d0;
output  [5:0] localC_V_59_address0;
output   localC_V_59_ce0;
output   localC_V_59_we0;
output  [31:0] localC_V_59_d0;
output  [5:0] localC_V_60_address0;
output   localC_V_60_ce0;
output   localC_V_60_we0;
output  [31:0] localC_V_60_d0;
output  [5:0] localC_V_61_address0;
output   localC_V_61_ce0;
output   localC_V_61_we0;
output  [31:0] localC_V_61_d0;
output  [5:0] localC_V_62_address0;
output   localC_V_62_ce0;
output   localC_V_62_we0;
output  [31:0] localC_V_62_d0;
output  [5:0] localC_V_63_address0;
output   localC_V_63_ce0;
output   localC_V_63_we0;
output  [31:0] localC_V_63_d0;

reg ap_idle;
reg localC_V_ce0;
reg localC_V_we0;
reg localC_V_1_ce0;
reg localC_V_1_we0;
reg localC_V_2_ce0;
reg localC_V_2_we0;
reg localC_V_3_ce0;
reg localC_V_3_we0;
reg localC_V_4_ce0;
reg localC_V_4_we0;
reg localC_V_5_ce0;
reg localC_V_5_we0;
reg localC_V_6_ce0;
reg localC_V_6_we0;
reg localC_V_7_ce0;
reg localC_V_7_we0;
reg localC_V_8_ce0;
reg localC_V_8_we0;
reg localC_V_9_ce0;
reg localC_V_9_we0;
reg localC_V_10_ce0;
reg localC_V_10_we0;
reg localC_V_11_ce0;
reg localC_V_11_we0;
reg localC_V_12_ce0;
reg localC_V_12_we0;
reg localC_V_13_ce0;
reg localC_V_13_we0;
reg localC_V_14_ce0;
reg localC_V_14_we0;
reg localC_V_15_ce0;
reg localC_V_15_we0;
reg localC_V_16_ce0;
reg localC_V_16_we0;
reg localC_V_17_ce0;
reg localC_V_17_we0;
reg localC_V_18_ce0;
reg localC_V_18_we0;
reg localC_V_19_ce0;
reg localC_V_19_we0;
reg localC_V_20_ce0;
reg localC_V_20_we0;
reg localC_V_21_ce0;
reg localC_V_21_we0;
reg localC_V_22_ce0;
reg localC_V_22_we0;
reg localC_V_23_ce0;
reg localC_V_23_we0;
reg localC_V_24_ce0;
reg localC_V_24_we0;
reg localC_V_25_ce0;
reg localC_V_25_we0;
reg localC_V_26_ce0;
reg localC_V_26_we0;
reg localC_V_27_ce0;
reg localC_V_27_we0;
reg localC_V_28_ce0;
reg localC_V_28_we0;
reg localC_V_29_ce0;
reg localC_V_29_we0;
reg localC_V_30_ce0;
reg localC_V_30_we0;
reg localC_V_31_ce0;
reg localC_V_31_we0;
reg localC_V_32_ce0;
reg localC_V_32_we0;
reg localC_V_33_ce0;
reg localC_V_33_we0;
reg localC_V_34_ce0;
reg localC_V_34_we0;
reg localC_V_35_ce0;
reg localC_V_35_we0;
reg localC_V_36_ce0;
reg localC_V_36_we0;
reg localC_V_37_ce0;
reg localC_V_37_we0;
reg localC_V_38_ce0;
reg localC_V_38_we0;
reg localC_V_39_ce0;
reg localC_V_39_we0;
reg localC_V_40_ce0;
reg localC_V_40_we0;
reg localC_V_41_ce0;
reg localC_V_41_we0;
reg localC_V_42_ce0;
reg localC_V_42_we0;
reg localC_V_43_ce0;
reg localC_V_43_we0;
reg localC_V_44_ce0;
reg localC_V_44_we0;
reg localC_V_45_ce0;
reg localC_V_45_we0;
reg localC_V_46_ce0;
reg localC_V_46_we0;
reg localC_V_47_ce0;
reg localC_V_47_we0;
reg localC_V_48_ce0;
reg localC_V_48_we0;
reg localC_V_49_ce0;
reg localC_V_49_we0;
reg localC_V_50_ce0;
reg localC_V_50_we0;
reg localC_V_51_ce0;
reg localC_V_51_we0;
reg localC_V_52_ce0;
reg localC_V_52_we0;
reg localC_V_53_ce0;
reg localC_V_53_we0;
reg localC_V_54_ce0;
reg localC_V_54_we0;
reg localC_V_55_ce0;
reg localC_V_55_we0;
reg localC_V_56_ce0;
reg localC_V_56_we0;
reg localC_V_57_ce0;
reg localC_V_57_we0;
reg localC_V_58_ce0;
reg localC_V_58_we0;
reg localC_V_59_ce0;
reg localC_V_59_we0;
reg localC_V_60_ce0;
reg localC_V_60_we0;
reg localC_V_61_ce0;
reg localC_V_61_we0;
reg localC_V_62_ce0;
reg localC_V_62_we0;
reg localC_V_63_ce0;
reg localC_V_63_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln39_fu_1212_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln39_fu_1258_p1;
wire   [5:0] trunc_ln42_fu_1326_p1;
reg   [6:0] j_fu_286;
wire   [6:0] add_ln40_fu_1330_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_290;
wire   [6:0] select_ln39_1_fu_1250_p3;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [12:0] indvar_flatten210_fu_294;
wire   [12:0] add_ln39_fu_1218_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten210_load;
wire   [0:0] icmp_ln40_fu_1230_p2;
wire   [6:0] add_ln39_1_fu_1244_p2;
wire   [6:0] select_ln39_fu_1236_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

systolic_4x4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln39_fu_1212_p2 == 1'd0)) begin
            i_fu_290 <= select_ln39_1_fu_1250_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_290 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln39_fu_1212_p2 == 1'd0)) begin
            indvar_flatten210_fu_294 <= add_ln39_fu_1218_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten210_fu_294 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln39_fu_1212_p2 == 1'd0)) begin
            j_fu_286 <= add_ln40_fu_1330_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_286 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln39_fu_1212_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_290;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten210_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten210_load = indvar_flatten210_fu_294;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_286;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_10_ce0 = 1'b1;
    end else begin
        localC_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd10) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_10_we0 = 1'b1;
    end else begin
        localC_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_11_ce0 = 1'b1;
    end else begin
        localC_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd11) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_11_we0 = 1'b1;
    end else begin
        localC_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_12_ce0 = 1'b1;
    end else begin
        localC_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd12) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_12_we0 = 1'b1;
    end else begin
        localC_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_13_ce0 = 1'b1;
    end else begin
        localC_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd13) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_13_we0 = 1'b1;
    end else begin
        localC_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_14_ce0 = 1'b1;
    end else begin
        localC_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd14) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_14_we0 = 1'b1;
    end else begin
        localC_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_15_ce0 = 1'b1;
    end else begin
        localC_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd15) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_15_we0 = 1'b1;
    end else begin
        localC_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_16_ce0 = 1'b1;
    end else begin
        localC_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd16) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_16_we0 = 1'b1;
    end else begin
        localC_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_17_ce0 = 1'b1;
    end else begin
        localC_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd17) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_17_we0 = 1'b1;
    end else begin
        localC_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_18_ce0 = 1'b1;
    end else begin
        localC_V_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd18) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_18_we0 = 1'b1;
    end else begin
        localC_V_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_19_ce0 = 1'b1;
    end else begin
        localC_V_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd19) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_19_we0 = 1'b1;
    end else begin
        localC_V_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_1_ce0 = 1'b1;
    end else begin
        localC_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd1) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_1_we0 = 1'b1;
    end else begin
        localC_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_20_ce0 = 1'b1;
    end else begin
        localC_V_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd20) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_20_we0 = 1'b1;
    end else begin
        localC_V_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_21_ce0 = 1'b1;
    end else begin
        localC_V_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd21) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_21_we0 = 1'b1;
    end else begin
        localC_V_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_22_ce0 = 1'b1;
    end else begin
        localC_V_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd22) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_22_we0 = 1'b1;
    end else begin
        localC_V_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_23_ce0 = 1'b1;
    end else begin
        localC_V_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd23) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_23_we0 = 1'b1;
    end else begin
        localC_V_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_24_ce0 = 1'b1;
    end else begin
        localC_V_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd24) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_24_we0 = 1'b1;
    end else begin
        localC_V_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_25_ce0 = 1'b1;
    end else begin
        localC_V_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd25) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_25_we0 = 1'b1;
    end else begin
        localC_V_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_26_ce0 = 1'b1;
    end else begin
        localC_V_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd26) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_26_we0 = 1'b1;
    end else begin
        localC_V_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_27_ce0 = 1'b1;
    end else begin
        localC_V_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd27) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_27_we0 = 1'b1;
    end else begin
        localC_V_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_28_ce0 = 1'b1;
    end else begin
        localC_V_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd28) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_28_we0 = 1'b1;
    end else begin
        localC_V_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_29_ce0 = 1'b1;
    end else begin
        localC_V_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd29) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_29_we0 = 1'b1;
    end else begin
        localC_V_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_2_ce0 = 1'b1;
    end else begin
        localC_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd2) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_2_we0 = 1'b1;
    end else begin
        localC_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_30_ce0 = 1'b1;
    end else begin
        localC_V_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd30) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_30_we0 = 1'b1;
    end else begin
        localC_V_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_31_ce0 = 1'b1;
    end else begin
        localC_V_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd31) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_31_we0 = 1'b1;
    end else begin
        localC_V_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_32_ce0 = 1'b1;
    end else begin
        localC_V_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd32) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_32_we0 = 1'b1;
    end else begin
        localC_V_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_33_ce0 = 1'b1;
    end else begin
        localC_V_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd33) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_33_we0 = 1'b1;
    end else begin
        localC_V_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_34_ce0 = 1'b1;
    end else begin
        localC_V_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd34) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_34_we0 = 1'b1;
    end else begin
        localC_V_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_35_ce0 = 1'b1;
    end else begin
        localC_V_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd35) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_35_we0 = 1'b1;
    end else begin
        localC_V_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_36_ce0 = 1'b1;
    end else begin
        localC_V_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd36) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_36_we0 = 1'b1;
    end else begin
        localC_V_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_37_ce0 = 1'b1;
    end else begin
        localC_V_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd37) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_37_we0 = 1'b1;
    end else begin
        localC_V_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_38_ce0 = 1'b1;
    end else begin
        localC_V_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd38) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_38_we0 = 1'b1;
    end else begin
        localC_V_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_39_ce0 = 1'b1;
    end else begin
        localC_V_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd39) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_39_we0 = 1'b1;
    end else begin
        localC_V_39_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_3_ce0 = 1'b1;
    end else begin
        localC_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd3) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_3_we0 = 1'b1;
    end else begin
        localC_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_40_ce0 = 1'b1;
    end else begin
        localC_V_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd40) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_40_we0 = 1'b1;
    end else begin
        localC_V_40_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_41_ce0 = 1'b1;
    end else begin
        localC_V_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd41) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_41_we0 = 1'b1;
    end else begin
        localC_V_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_42_ce0 = 1'b1;
    end else begin
        localC_V_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd42) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_42_we0 = 1'b1;
    end else begin
        localC_V_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_43_ce0 = 1'b1;
    end else begin
        localC_V_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd43) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_43_we0 = 1'b1;
    end else begin
        localC_V_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_44_ce0 = 1'b1;
    end else begin
        localC_V_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd44) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_44_we0 = 1'b1;
    end else begin
        localC_V_44_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_45_ce0 = 1'b1;
    end else begin
        localC_V_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd45) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_45_we0 = 1'b1;
    end else begin
        localC_V_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_46_ce0 = 1'b1;
    end else begin
        localC_V_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd46) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_46_we0 = 1'b1;
    end else begin
        localC_V_46_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_47_ce0 = 1'b1;
    end else begin
        localC_V_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd47) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_47_we0 = 1'b1;
    end else begin
        localC_V_47_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_48_ce0 = 1'b1;
    end else begin
        localC_V_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd48) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_48_we0 = 1'b1;
    end else begin
        localC_V_48_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_49_ce0 = 1'b1;
    end else begin
        localC_V_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd49) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_49_we0 = 1'b1;
    end else begin
        localC_V_49_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_4_ce0 = 1'b1;
    end else begin
        localC_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd4) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_4_we0 = 1'b1;
    end else begin
        localC_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_50_ce0 = 1'b1;
    end else begin
        localC_V_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd50) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_50_we0 = 1'b1;
    end else begin
        localC_V_50_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_51_ce0 = 1'b1;
    end else begin
        localC_V_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd51) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_51_we0 = 1'b1;
    end else begin
        localC_V_51_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_52_ce0 = 1'b1;
    end else begin
        localC_V_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd52) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_52_we0 = 1'b1;
    end else begin
        localC_V_52_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_53_ce0 = 1'b1;
    end else begin
        localC_V_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd53) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_53_we0 = 1'b1;
    end else begin
        localC_V_53_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_54_ce0 = 1'b1;
    end else begin
        localC_V_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd54) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_54_we0 = 1'b1;
    end else begin
        localC_V_54_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_55_ce0 = 1'b1;
    end else begin
        localC_V_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd55) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_55_we0 = 1'b1;
    end else begin
        localC_V_55_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_56_ce0 = 1'b1;
    end else begin
        localC_V_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd56) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_56_we0 = 1'b1;
    end else begin
        localC_V_56_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_57_ce0 = 1'b1;
    end else begin
        localC_V_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd57) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_57_we0 = 1'b1;
    end else begin
        localC_V_57_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_58_ce0 = 1'b1;
    end else begin
        localC_V_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd58) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_58_we0 = 1'b1;
    end else begin
        localC_V_58_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_59_ce0 = 1'b1;
    end else begin
        localC_V_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd59) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_59_we0 = 1'b1;
    end else begin
        localC_V_59_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_5_ce0 = 1'b1;
    end else begin
        localC_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd5) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_5_we0 = 1'b1;
    end else begin
        localC_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_60_ce0 = 1'b1;
    end else begin
        localC_V_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd60) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_60_we0 = 1'b1;
    end else begin
        localC_V_60_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_61_ce0 = 1'b1;
    end else begin
        localC_V_61_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd61) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_61_we0 = 1'b1;
    end else begin
        localC_V_61_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_62_ce0 = 1'b1;
    end else begin
        localC_V_62_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd62) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_62_we0 = 1'b1;
    end else begin
        localC_V_62_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_63_ce0 = 1'b1;
    end else begin
        localC_V_63_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd63) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_63_we0 = 1'b1;
    end else begin
        localC_V_63_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_6_ce0 = 1'b1;
    end else begin
        localC_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd6) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_6_we0 = 1'b1;
    end else begin
        localC_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_7_ce0 = 1'b1;
    end else begin
        localC_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd7) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_7_we0 = 1'b1;
    end else begin
        localC_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_8_ce0 = 1'b1;
    end else begin
        localC_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd8) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_8_we0 = 1'b1;
    end else begin
        localC_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_9_ce0 = 1'b1;
    end else begin
        localC_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd9) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_9_we0 = 1'b1;
    end else begin
        localC_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_ce0 = 1'b1;
    end else begin
        localC_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (trunc_ln42_fu_1326_p1 == 6'd0) & (icmp_ln39_fu_1212_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        localC_V_we0 = 1'b1;
    end else begin
        localC_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_1_fu_1244_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign add_ln39_fu_1218_p2 = (ap_sig_allocacmp_indvar_flatten210_load + 13'd1);

assign add_ln40_fu_1330_p2 = (select_ln39_fu_1236_p3 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln39_fu_1212_p2 = ((ap_sig_allocacmp_indvar_flatten210_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_1230_p2 = ((ap_sig_allocacmp_j_load == 7'd64) ? 1'b1 : 1'b0);

assign localC_V_10_address0 = zext_ln39_fu_1258_p1;

assign localC_V_10_d0 = 32'd0;

assign localC_V_11_address0 = zext_ln39_fu_1258_p1;

assign localC_V_11_d0 = 32'd0;

assign localC_V_12_address0 = zext_ln39_fu_1258_p1;

assign localC_V_12_d0 = 32'd0;

assign localC_V_13_address0 = zext_ln39_fu_1258_p1;

assign localC_V_13_d0 = 32'd0;

assign localC_V_14_address0 = zext_ln39_fu_1258_p1;

assign localC_V_14_d0 = 32'd0;

assign localC_V_15_address0 = zext_ln39_fu_1258_p1;

assign localC_V_15_d0 = 32'd0;

assign localC_V_16_address0 = zext_ln39_fu_1258_p1;

assign localC_V_16_d0 = 32'd0;

assign localC_V_17_address0 = zext_ln39_fu_1258_p1;

assign localC_V_17_d0 = 32'd0;

assign localC_V_18_address0 = zext_ln39_fu_1258_p1;

assign localC_V_18_d0 = 32'd0;

assign localC_V_19_address0 = zext_ln39_fu_1258_p1;

assign localC_V_19_d0 = 32'd0;

assign localC_V_1_address0 = zext_ln39_fu_1258_p1;

assign localC_V_1_d0 = 32'd0;

assign localC_V_20_address0 = zext_ln39_fu_1258_p1;

assign localC_V_20_d0 = 32'd0;

assign localC_V_21_address0 = zext_ln39_fu_1258_p1;

assign localC_V_21_d0 = 32'd0;

assign localC_V_22_address0 = zext_ln39_fu_1258_p1;

assign localC_V_22_d0 = 32'd0;

assign localC_V_23_address0 = zext_ln39_fu_1258_p1;

assign localC_V_23_d0 = 32'd0;

assign localC_V_24_address0 = zext_ln39_fu_1258_p1;

assign localC_V_24_d0 = 32'd0;

assign localC_V_25_address0 = zext_ln39_fu_1258_p1;

assign localC_V_25_d0 = 32'd0;

assign localC_V_26_address0 = zext_ln39_fu_1258_p1;

assign localC_V_26_d0 = 32'd0;

assign localC_V_27_address0 = zext_ln39_fu_1258_p1;

assign localC_V_27_d0 = 32'd0;

assign localC_V_28_address0 = zext_ln39_fu_1258_p1;

assign localC_V_28_d0 = 32'd0;

assign localC_V_29_address0 = zext_ln39_fu_1258_p1;

assign localC_V_29_d0 = 32'd0;

assign localC_V_2_address0 = zext_ln39_fu_1258_p1;

assign localC_V_2_d0 = 32'd0;

assign localC_V_30_address0 = zext_ln39_fu_1258_p1;

assign localC_V_30_d0 = 32'd0;

assign localC_V_31_address0 = zext_ln39_fu_1258_p1;

assign localC_V_31_d0 = 32'd0;

assign localC_V_32_address0 = zext_ln39_fu_1258_p1;

assign localC_V_32_d0 = 32'd0;

assign localC_V_33_address0 = zext_ln39_fu_1258_p1;

assign localC_V_33_d0 = 32'd0;

assign localC_V_34_address0 = zext_ln39_fu_1258_p1;

assign localC_V_34_d0 = 32'd0;

assign localC_V_35_address0 = zext_ln39_fu_1258_p1;

assign localC_V_35_d0 = 32'd0;

assign localC_V_36_address0 = zext_ln39_fu_1258_p1;

assign localC_V_36_d0 = 32'd0;

assign localC_V_37_address0 = zext_ln39_fu_1258_p1;

assign localC_V_37_d0 = 32'd0;

assign localC_V_38_address0 = zext_ln39_fu_1258_p1;

assign localC_V_38_d0 = 32'd0;

assign localC_V_39_address0 = zext_ln39_fu_1258_p1;

assign localC_V_39_d0 = 32'd0;

assign localC_V_3_address0 = zext_ln39_fu_1258_p1;

assign localC_V_3_d0 = 32'd0;

assign localC_V_40_address0 = zext_ln39_fu_1258_p1;

assign localC_V_40_d0 = 32'd0;

assign localC_V_41_address0 = zext_ln39_fu_1258_p1;

assign localC_V_41_d0 = 32'd0;

assign localC_V_42_address0 = zext_ln39_fu_1258_p1;

assign localC_V_42_d0 = 32'd0;

assign localC_V_43_address0 = zext_ln39_fu_1258_p1;

assign localC_V_43_d0 = 32'd0;

assign localC_V_44_address0 = zext_ln39_fu_1258_p1;

assign localC_V_44_d0 = 32'd0;

assign localC_V_45_address0 = zext_ln39_fu_1258_p1;

assign localC_V_45_d0 = 32'd0;

assign localC_V_46_address0 = zext_ln39_fu_1258_p1;

assign localC_V_46_d0 = 32'd0;

assign localC_V_47_address0 = zext_ln39_fu_1258_p1;

assign localC_V_47_d0 = 32'd0;

assign localC_V_48_address0 = zext_ln39_fu_1258_p1;

assign localC_V_48_d0 = 32'd0;

assign localC_V_49_address0 = zext_ln39_fu_1258_p1;

assign localC_V_49_d0 = 32'd0;

assign localC_V_4_address0 = zext_ln39_fu_1258_p1;

assign localC_V_4_d0 = 32'd0;

assign localC_V_50_address0 = zext_ln39_fu_1258_p1;

assign localC_V_50_d0 = 32'd0;

assign localC_V_51_address0 = zext_ln39_fu_1258_p1;

assign localC_V_51_d0 = 32'd0;

assign localC_V_52_address0 = zext_ln39_fu_1258_p1;

assign localC_V_52_d0 = 32'd0;

assign localC_V_53_address0 = zext_ln39_fu_1258_p1;

assign localC_V_53_d0 = 32'd0;

assign localC_V_54_address0 = zext_ln39_fu_1258_p1;

assign localC_V_54_d0 = 32'd0;

assign localC_V_55_address0 = zext_ln39_fu_1258_p1;

assign localC_V_55_d0 = 32'd0;

assign localC_V_56_address0 = zext_ln39_fu_1258_p1;

assign localC_V_56_d0 = 32'd0;

assign localC_V_57_address0 = zext_ln39_fu_1258_p1;

assign localC_V_57_d0 = 32'd0;

assign localC_V_58_address0 = zext_ln39_fu_1258_p1;

assign localC_V_58_d0 = 32'd0;

assign localC_V_59_address0 = zext_ln39_fu_1258_p1;

assign localC_V_59_d0 = 32'd0;

assign localC_V_5_address0 = zext_ln39_fu_1258_p1;

assign localC_V_5_d0 = 32'd0;

assign localC_V_60_address0 = zext_ln39_fu_1258_p1;

assign localC_V_60_d0 = 32'd0;

assign localC_V_61_address0 = zext_ln39_fu_1258_p1;

assign localC_V_61_d0 = 32'd0;

assign localC_V_62_address0 = zext_ln39_fu_1258_p1;

assign localC_V_62_d0 = 32'd0;

assign localC_V_63_address0 = zext_ln39_fu_1258_p1;

assign localC_V_63_d0 = 32'd0;

assign localC_V_6_address0 = zext_ln39_fu_1258_p1;

assign localC_V_6_d0 = 32'd0;

assign localC_V_7_address0 = zext_ln39_fu_1258_p1;

assign localC_V_7_d0 = 32'd0;

assign localC_V_8_address0 = zext_ln39_fu_1258_p1;

assign localC_V_8_d0 = 32'd0;

assign localC_V_9_address0 = zext_ln39_fu_1258_p1;

assign localC_V_9_d0 = 32'd0;

assign localC_V_address0 = zext_ln39_fu_1258_p1;

assign localC_V_d0 = 32'd0;

assign select_ln39_1_fu_1250_p3 = ((icmp_ln40_fu_1230_p2[0:0] == 1'b1) ? add_ln39_1_fu_1244_p2 : ap_sig_allocacmp_i_load);

assign select_ln39_fu_1236_p3 = ((icmp_ln40_fu_1230_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign trunc_ln42_fu_1326_p1 = select_ln39_fu_1236_p3[5:0];

assign zext_ln39_fu_1258_p1 = select_ln39_1_fu_1250_p3;

endmodule //systolic_4x4_systolic_4x4_Pipeline_VITIS_LOOP_39_5_VITIS_LOOP_40_6
