// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module systolic_4x4_systolic_4x4_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        localB_V_address0,
        localB_V_ce0,
        localB_V_we0,
        localB_V_d0,
        B_mem_Addr_A,
        B_mem_EN_A,
        B_mem_WEN_A,
        B_mem_Din_A,
        B_mem_Dout_A,
        localB_V_1_address0,
        localB_V_1_ce0,
        localB_V_1_we0,
        localB_V_1_d0,
        localB_V_2_address0,
        localB_V_2_ce0,
        localB_V_2_we0,
        localB_V_2_d0,
        localB_V_3_address0,
        localB_V_3_ce0,
        localB_V_3_we0,
        localB_V_3_d0,
        localB_V_4_address0,
        localB_V_4_ce0,
        localB_V_4_we0,
        localB_V_4_d0,
        localB_V_5_address0,
        localB_V_5_ce0,
        localB_V_5_we0,
        localB_V_5_d0,
        localB_V_6_address0,
        localB_V_6_ce0,
        localB_V_6_we0,
        localB_V_6_d0,
        localB_V_7_address0,
        localB_V_7_ce0,
        localB_V_7_we0,
        localB_V_7_d0,
        localB_V_8_address0,
        localB_V_8_ce0,
        localB_V_8_we0,
        localB_V_8_d0,
        localB_V_9_address0,
        localB_V_9_ce0,
        localB_V_9_we0,
        localB_V_9_d0,
        localB_V_10_address0,
        localB_V_10_ce0,
        localB_V_10_we0,
        localB_V_10_d0,
        localB_V_11_address0,
        localB_V_11_ce0,
        localB_V_11_we0,
        localB_V_11_d0,
        localB_V_12_address0,
        localB_V_12_ce0,
        localB_V_12_we0,
        localB_V_12_d0,
        localB_V_13_address0,
        localB_V_13_ce0,
        localB_V_13_we0,
        localB_V_13_d0,
        localB_V_14_address0,
        localB_V_14_ce0,
        localB_V_14_we0,
        localB_V_14_d0,
        localB_V_15_address0,
        localB_V_15_ce0,
        localB_V_15_we0,
        localB_V_15_d0,
        localB_V_16_address0,
        localB_V_16_ce0,
        localB_V_16_we0,
        localB_V_16_d0,
        localB_V_17_address0,
        localB_V_17_ce0,
        localB_V_17_we0,
        localB_V_17_d0,
        localB_V_18_address0,
        localB_V_18_ce0,
        localB_V_18_we0,
        localB_V_18_d0,
        localB_V_19_address0,
        localB_V_19_ce0,
        localB_V_19_we0,
        localB_V_19_d0,
        localB_V_20_address0,
        localB_V_20_ce0,
        localB_V_20_we0,
        localB_V_20_d0,
        localB_V_21_address0,
        localB_V_21_ce0,
        localB_V_21_we0,
        localB_V_21_d0,
        localB_V_22_address0,
        localB_V_22_ce0,
        localB_V_22_we0,
        localB_V_22_d0,
        localB_V_23_address0,
        localB_V_23_ce0,
        localB_V_23_we0,
        localB_V_23_d0,
        localB_V_24_address0,
        localB_V_24_ce0,
        localB_V_24_we0,
        localB_V_24_d0,
        localB_V_25_address0,
        localB_V_25_ce0,
        localB_V_25_we0,
        localB_V_25_d0,
        localB_V_26_address0,
        localB_V_26_ce0,
        localB_V_26_we0,
        localB_V_26_d0,
        localB_V_27_address0,
        localB_V_27_ce0,
        localB_V_27_we0,
        localB_V_27_d0,
        localB_V_28_address0,
        localB_V_28_ce0,
        localB_V_28_we0,
        localB_V_28_d0,
        localB_V_29_address0,
        localB_V_29_ce0,
        localB_V_29_we0,
        localB_V_29_d0,
        localB_V_30_address0,
        localB_V_30_ce0,
        localB_V_30_we0,
        localB_V_30_d0,
        localB_V_31_address0,
        localB_V_31_ce0,
        localB_V_31_we0,
        localB_V_31_d0,
        localB_V_32_address0,
        localB_V_32_ce0,
        localB_V_32_we0,
        localB_V_32_d0,
        localB_V_33_address0,
        localB_V_33_ce0,
        localB_V_33_we0,
        localB_V_33_d0,
        localB_V_34_address0,
        localB_V_34_ce0,
        localB_V_34_we0,
        localB_V_34_d0,
        localB_V_35_address0,
        localB_V_35_ce0,
        localB_V_35_we0,
        localB_V_35_d0,
        localB_V_36_address0,
        localB_V_36_ce0,
        localB_V_36_we0,
        localB_V_36_d0,
        localB_V_37_address0,
        localB_V_37_ce0,
        localB_V_37_we0,
        localB_V_37_d0,
        localB_V_38_address0,
        localB_V_38_ce0,
        localB_V_38_we0,
        localB_V_38_d0,
        localB_V_39_address0,
        localB_V_39_ce0,
        localB_V_39_we0,
        localB_V_39_d0,
        localB_V_40_address0,
        localB_V_40_ce0,
        localB_V_40_we0,
        localB_V_40_d0,
        localB_V_41_address0,
        localB_V_41_ce0,
        localB_V_41_we0,
        localB_V_41_d0,
        localB_V_42_address0,
        localB_V_42_ce0,
        localB_V_42_we0,
        localB_V_42_d0,
        localB_V_43_address0,
        localB_V_43_ce0,
        localB_V_43_we0,
        localB_V_43_d0,
        localB_V_44_address0,
        localB_V_44_ce0,
        localB_V_44_we0,
        localB_V_44_d0,
        localB_V_45_address0,
        localB_V_45_ce0,
        localB_V_45_we0,
        localB_V_45_d0,
        localB_V_46_address0,
        localB_V_46_ce0,
        localB_V_46_we0,
        localB_V_46_d0,
        localB_V_47_address0,
        localB_V_47_ce0,
        localB_V_47_we0,
        localB_V_47_d0,
        localB_V_48_address0,
        localB_V_48_ce0,
        localB_V_48_we0,
        localB_V_48_d0,
        localB_V_49_address0,
        localB_V_49_ce0,
        localB_V_49_we0,
        localB_V_49_d0,
        localB_V_50_address0,
        localB_V_50_ce0,
        localB_V_50_we0,
        localB_V_50_d0,
        localB_V_51_address0,
        localB_V_51_ce0,
        localB_V_51_we0,
        localB_V_51_d0,
        localB_V_52_address0,
        localB_V_52_ce0,
        localB_V_52_we0,
        localB_V_52_d0,
        localB_V_53_address0,
        localB_V_53_ce0,
        localB_V_53_we0,
        localB_V_53_d0,
        localB_V_54_address0,
        localB_V_54_ce0,
        localB_V_54_we0,
        localB_V_54_d0,
        localB_V_55_address0,
        localB_V_55_ce0,
        localB_V_55_we0,
        localB_V_55_d0,
        localB_V_56_address0,
        localB_V_56_ce0,
        localB_V_56_we0,
        localB_V_56_d0,
        localB_V_57_address0,
        localB_V_57_ce0,
        localB_V_57_we0,
        localB_V_57_d0,
        localB_V_58_address0,
        localB_V_58_ce0,
        localB_V_58_we0,
        localB_V_58_d0,
        localB_V_59_address0,
        localB_V_59_ce0,
        localB_V_59_we0,
        localB_V_59_d0,
        localB_V_60_address0,
        localB_V_60_ce0,
        localB_V_60_we0,
        localB_V_60_d0,
        localB_V_61_address0,
        localB_V_61_ce0,
        localB_V_61_we0,
        localB_V_61_d0,
        localB_V_62_address0,
        localB_V_62_ce0,
        localB_V_62_we0,
        localB_V_62_d0,
        localB_V_63_address0,
        localB_V_63_ce0,
        localB_V_63_we0,
        localB_V_63_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] localB_V_address0;
output   localB_V_ce0;
output   localB_V_we0;
output  [7:0] localB_V_d0;
output  [31:0] B_mem_Addr_A;
output   B_mem_EN_A;
output  [0:0] B_mem_WEN_A;
output  [7:0] B_mem_Din_A;
input  [7:0] B_mem_Dout_A;
output  [5:0] localB_V_1_address0;
output   localB_V_1_ce0;
output   localB_V_1_we0;
output  [7:0] localB_V_1_d0;
output  [5:0] localB_V_2_address0;
output   localB_V_2_ce0;
output   localB_V_2_we0;
output  [7:0] localB_V_2_d0;
output  [5:0] localB_V_3_address0;
output   localB_V_3_ce0;
output   localB_V_3_we0;
output  [7:0] localB_V_3_d0;
output  [5:0] localB_V_4_address0;
output   localB_V_4_ce0;
output   localB_V_4_we0;
output  [7:0] localB_V_4_d0;
output  [5:0] localB_V_5_address0;
output   localB_V_5_ce0;
output   localB_V_5_we0;
output  [7:0] localB_V_5_d0;
output  [5:0] localB_V_6_address0;
output   localB_V_6_ce0;
output   localB_V_6_we0;
output  [7:0] localB_V_6_d0;
output  [5:0] localB_V_7_address0;
output   localB_V_7_ce0;
output   localB_V_7_we0;
output  [7:0] localB_V_7_d0;
output  [5:0] localB_V_8_address0;
output   localB_V_8_ce0;
output   localB_V_8_we0;
output  [7:0] localB_V_8_d0;
output  [5:0] localB_V_9_address0;
output   localB_V_9_ce0;
output   localB_V_9_we0;
output  [7:0] localB_V_9_d0;
output  [5:0] localB_V_10_address0;
output   localB_V_10_ce0;
output   localB_V_10_we0;
output  [7:0] localB_V_10_d0;
output  [5:0] localB_V_11_address0;
output   localB_V_11_ce0;
output   localB_V_11_we0;
output  [7:0] localB_V_11_d0;
output  [5:0] localB_V_12_address0;
output   localB_V_12_ce0;
output   localB_V_12_we0;
output  [7:0] localB_V_12_d0;
output  [5:0] localB_V_13_address0;
output   localB_V_13_ce0;
output   localB_V_13_we0;
output  [7:0] localB_V_13_d0;
output  [5:0] localB_V_14_address0;
output   localB_V_14_ce0;
output   localB_V_14_we0;
output  [7:0] localB_V_14_d0;
output  [5:0] localB_V_15_address0;
output   localB_V_15_ce0;
output   localB_V_15_we0;
output  [7:0] localB_V_15_d0;
output  [5:0] localB_V_16_address0;
output   localB_V_16_ce0;
output   localB_V_16_we0;
output  [7:0] localB_V_16_d0;
output  [5:0] localB_V_17_address0;
output   localB_V_17_ce0;
output   localB_V_17_we0;
output  [7:0] localB_V_17_d0;
output  [5:0] localB_V_18_address0;
output   localB_V_18_ce0;
output   localB_V_18_we0;
output  [7:0] localB_V_18_d0;
output  [5:0] localB_V_19_address0;
output   localB_V_19_ce0;
output   localB_V_19_we0;
output  [7:0] localB_V_19_d0;
output  [5:0] localB_V_20_address0;
output   localB_V_20_ce0;
output   localB_V_20_we0;
output  [7:0] localB_V_20_d0;
output  [5:0] localB_V_21_address0;
output   localB_V_21_ce0;
output   localB_V_21_we0;
output  [7:0] localB_V_21_d0;
output  [5:0] localB_V_22_address0;
output   localB_V_22_ce0;
output   localB_V_22_we0;
output  [7:0] localB_V_22_d0;
output  [5:0] localB_V_23_address0;
output   localB_V_23_ce0;
output   localB_V_23_we0;
output  [7:0] localB_V_23_d0;
output  [5:0] localB_V_24_address0;
output   localB_V_24_ce0;
output   localB_V_24_we0;
output  [7:0] localB_V_24_d0;
output  [5:0] localB_V_25_address0;
output   localB_V_25_ce0;
output   localB_V_25_we0;
output  [7:0] localB_V_25_d0;
output  [5:0] localB_V_26_address0;
output   localB_V_26_ce0;
output   localB_V_26_we0;
output  [7:0] localB_V_26_d0;
output  [5:0] localB_V_27_address0;
output   localB_V_27_ce0;
output   localB_V_27_we0;
output  [7:0] localB_V_27_d0;
output  [5:0] localB_V_28_address0;
output   localB_V_28_ce0;
output   localB_V_28_we0;
output  [7:0] localB_V_28_d0;
output  [5:0] localB_V_29_address0;
output   localB_V_29_ce0;
output   localB_V_29_we0;
output  [7:0] localB_V_29_d0;
output  [5:0] localB_V_30_address0;
output   localB_V_30_ce0;
output   localB_V_30_we0;
output  [7:0] localB_V_30_d0;
output  [5:0] localB_V_31_address0;
output   localB_V_31_ce0;
output   localB_V_31_we0;
output  [7:0] localB_V_31_d0;
output  [5:0] localB_V_32_address0;
output   localB_V_32_ce0;
output   localB_V_32_we0;
output  [7:0] localB_V_32_d0;
output  [5:0] localB_V_33_address0;
output   localB_V_33_ce0;
output   localB_V_33_we0;
output  [7:0] localB_V_33_d0;
output  [5:0] localB_V_34_address0;
output   localB_V_34_ce0;
output   localB_V_34_we0;
output  [7:0] localB_V_34_d0;
output  [5:0] localB_V_35_address0;
output   localB_V_35_ce0;
output   localB_V_35_we0;
output  [7:0] localB_V_35_d0;
output  [5:0] localB_V_36_address0;
output   localB_V_36_ce0;
output   localB_V_36_we0;
output  [7:0] localB_V_36_d0;
output  [5:0] localB_V_37_address0;
output   localB_V_37_ce0;
output   localB_V_37_we0;
output  [7:0] localB_V_37_d0;
output  [5:0] localB_V_38_address0;
output   localB_V_38_ce0;
output   localB_V_38_we0;
output  [7:0] localB_V_38_d0;
output  [5:0] localB_V_39_address0;
output   localB_V_39_ce0;
output   localB_V_39_we0;
output  [7:0] localB_V_39_d0;
output  [5:0] localB_V_40_address0;
output   localB_V_40_ce0;
output   localB_V_40_we0;
output  [7:0] localB_V_40_d0;
output  [5:0] localB_V_41_address0;
output   localB_V_41_ce0;
output   localB_V_41_we0;
output  [7:0] localB_V_41_d0;
output  [5:0] localB_V_42_address0;
output   localB_V_42_ce0;
output   localB_V_42_we0;
output  [7:0] localB_V_42_d0;
output  [5:0] localB_V_43_address0;
output   localB_V_43_ce0;
output   localB_V_43_we0;
output  [7:0] localB_V_43_d0;
output  [5:0] localB_V_44_address0;
output   localB_V_44_ce0;
output   localB_V_44_we0;
output  [7:0] localB_V_44_d0;
output  [5:0] localB_V_45_address0;
output   localB_V_45_ce0;
output   localB_V_45_we0;
output  [7:0] localB_V_45_d0;
output  [5:0] localB_V_46_address0;
output   localB_V_46_ce0;
output   localB_V_46_we0;
output  [7:0] localB_V_46_d0;
output  [5:0] localB_V_47_address0;
output   localB_V_47_ce0;
output   localB_V_47_we0;
output  [7:0] localB_V_47_d0;
output  [5:0] localB_V_48_address0;
output   localB_V_48_ce0;
output   localB_V_48_we0;
output  [7:0] localB_V_48_d0;
output  [5:0] localB_V_49_address0;
output   localB_V_49_ce0;
output   localB_V_49_we0;
output  [7:0] localB_V_49_d0;
output  [5:0] localB_V_50_address0;
output   localB_V_50_ce0;
output   localB_V_50_we0;
output  [7:0] localB_V_50_d0;
output  [5:0] localB_V_51_address0;
output   localB_V_51_ce0;
output   localB_V_51_we0;
output  [7:0] localB_V_51_d0;
output  [5:0] localB_V_52_address0;
output   localB_V_52_ce0;
output   localB_V_52_we0;
output  [7:0] localB_V_52_d0;
output  [5:0] localB_V_53_address0;
output   localB_V_53_ce0;
output   localB_V_53_we0;
output  [7:0] localB_V_53_d0;
output  [5:0] localB_V_54_address0;
output   localB_V_54_ce0;
output   localB_V_54_we0;
output  [7:0] localB_V_54_d0;
output  [5:0] localB_V_55_address0;
output   localB_V_55_ce0;
output   localB_V_55_we0;
output  [7:0] localB_V_55_d0;
output  [5:0] localB_V_56_address0;
output   localB_V_56_ce0;
output   localB_V_56_we0;
output  [7:0] localB_V_56_d0;
output  [5:0] localB_V_57_address0;
output   localB_V_57_ce0;
output   localB_V_57_we0;
output  [7:0] localB_V_57_d0;
output  [5:0] localB_V_58_address0;
output   localB_V_58_ce0;
output   localB_V_58_we0;
output  [7:0] localB_V_58_d0;
output  [5:0] localB_V_59_address0;
output   localB_V_59_ce0;
output   localB_V_59_we0;
output  [7:0] localB_V_59_d0;
output  [5:0] localB_V_60_address0;
output   localB_V_60_ce0;
output   localB_V_60_we0;
output  [7:0] localB_V_60_d0;
output  [5:0] localB_V_61_address0;
output   localB_V_61_ce0;
output   localB_V_61_we0;
output  [7:0] localB_V_61_d0;
output  [5:0] localB_V_62_address0;
output   localB_V_62_ce0;
output   localB_V_62_we0;
output  [7:0] localB_V_62_d0;
output  [5:0] localB_V_63_address0;
output   localB_V_63_ce0;
output   localB_V_63_we0;
output  [7:0] localB_V_63_d0;

reg ap_idle;
reg localB_V_ce0;
reg localB_V_we0;
reg B_mem_EN_A;
reg localB_V_1_ce0;
reg localB_V_1_we0;
reg localB_V_2_ce0;
reg localB_V_2_we0;
reg localB_V_3_ce0;
reg localB_V_3_we0;
reg localB_V_4_ce0;
reg localB_V_4_we0;
reg localB_V_5_ce0;
reg localB_V_5_we0;
reg localB_V_6_ce0;
reg localB_V_6_we0;
reg localB_V_7_ce0;
reg localB_V_7_we0;
reg localB_V_8_ce0;
reg localB_V_8_we0;
reg localB_V_9_ce0;
reg localB_V_9_we0;
reg localB_V_10_ce0;
reg localB_V_10_we0;
reg localB_V_11_ce0;
reg localB_V_11_we0;
reg localB_V_12_ce0;
reg localB_V_12_we0;
reg localB_V_13_ce0;
reg localB_V_13_we0;
reg localB_V_14_ce0;
reg localB_V_14_we0;
reg localB_V_15_ce0;
reg localB_V_15_we0;
reg localB_V_16_ce0;
reg localB_V_16_we0;
reg localB_V_17_ce0;
reg localB_V_17_we0;
reg localB_V_18_ce0;
reg localB_V_18_we0;
reg localB_V_19_ce0;
reg localB_V_19_we0;
reg localB_V_20_ce0;
reg localB_V_20_we0;
reg localB_V_21_ce0;
reg localB_V_21_we0;
reg localB_V_22_ce0;
reg localB_V_22_we0;
reg localB_V_23_ce0;
reg localB_V_23_we0;
reg localB_V_24_ce0;
reg localB_V_24_we0;
reg localB_V_25_ce0;
reg localB_V_25_we0;
reg localB_V_26_ce0;
reg localB_V_26_we0;
reg localB_V_27_ce0;
reg localB_V_27_we0;
reg localB_V_28_ce0;
reg localB_V_28_we0;
reg localB_V_29_ce0;
reg localB_V_29_we0;
reg localB_V_30_ce0;
reg localB_V_30_we0;
reg localB_V_31_ce0;
reg localB_V_31_we0;
reg localB_V_32_ce0;
reg localB_V_32_we0;
reg localB_V_33_ce0;
reg localB_V_33_we0;
reg localB_V_34_ce0;
reg localB_V_34_we0;
reg localB_V_35_ce0;
reg localB_V_35_we0;
reg localB_V_36_ce0;
reg localB_V_36_we0;
reg localB_V_37_ce0;
reg localB_V_37_we0;
reg localB_V_38_ce0;
reg localB_V_38_we0;
reg localB_V_39_ce0;
reg localB_V_39_we0;
reg localB_V_40_ce0;
reg localB_V_40_we0;
reg localB_V_41_ce0;
reg localB_V_41_we0;
reg localB_V_42_ce0;
reg localB_V_42_we0;
reg localB_V_43_ce0;
reg localB_V_43_we0;
reg localB_V_44_ce0;
reg localB_V_44_we0;
reg localB_V_45_ce0;
reg localB_V_45_we0;
reg localB_V_46_ce0;
reg localB_V_46_we0;
reg localB_V_47_ce0;
reg localB_V_47_we0;
reg localB_V_48_ce0;
reg localB_V_48_we0;
reg localB_V_49_ce0;
reg localB_V_49_we0;
reg localB_V_50_ce0;
reg localB_V_50_we0;
reg localB_V_51_ce0;
reg localB_V_51_we0;
reg localB_V_52_ce0;
reg localB_V_52_we0;
reg localB_V_53_ce0;
reg localB_V_53_we0;
reg localB_V_54_ce0;
reg localB_V_54_we0;
reg localB_V_55_ce0;
reg localB_V_55_we0;
reg localB_V_56_ce0;
reg localB_V_56_we0;
reg localB_V_57_ce0;
reg localB_V_57_we0;
reg localB_V_58_ce0;
reg localB_V_58_we0;
reg localB_V_59_ce0;
reg localB_V_59_we0;
reg localB_V_60_ce0;
reg localB_V_60_we0;
reg localB_V_61_ce0;
reg localB_V_61_we0;
reg localB_V_62_ce0;
reg localB_V_62_we0;
reg localB_V_63_ce0;
reg localB_V_63_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln31_fu_1235_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] select_ln31_1_fu_1273_p3;
reg   [6:0] select_ln31_1_reg_1424;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] trunc_ln34_fu_1308_p1;
reg   [5:0] trunc_ln34_reg_1434;
wire   [63:0] zext_ln34_fu_1303_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln31_fu_1333_p1;
reg   [6:0] j_fu_296;
wire   [6:0] add_ln32_fu_1312_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_load;
reg   [6:0] i_fu_300;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [12:0] indvar_flatten138_fu_304;
wire   [12:0] add_ln31_fu_1241_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten138_load;
wire   [31:0] B_mem_Addr_A_orig;
wire   [0:0] icmp_ln32_fu_1253_p2;
wire   [6:0] add_ln31_1_fu_1267_p2;
wire   [5:0] trunc_ln31_fu_1281_p1;
wire   [6:0] select_ln31_fu_1259_p3;
wire   [11:0] zext_ln32_fu_1293_p1;
wire   [11:0] p_mid_fu_1285_p3;
wire   [11:0] add_ln18_fu_1297_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

systolic_4x4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln31_fu_1235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_300 <= select_ln31_1_fu_1273_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_300 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln31_fu_1235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten138_fu_304 <= add_ln31_fu_1241_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten138_fu_304 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln31_fu_1235_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_296 <= add_ln32_fu_1312_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_296 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln31_fu_1235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln31_1_reg_1424 <= select_ln31_1_fu_1273_p3;
        trunc_ln34_reg_1434 <= trunc_ln34_fu_1308_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_mem_EN_A = 1'b1;
    end else begin
        B_mem_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_1235_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_300;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten138_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten138_load = indvar_flatten138_fu_304;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_296;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_10_ce0 = 1'b1;
    end else begin
        localB_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_10_we0 = 1'b1;
    end else begin
        localB_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_11_ce0 = 1'b1;
    end else begin
        localB_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_11_we0 = 1'b1;
    end else begin
        localB_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_12_ce0 = 1'b1;
    end else begin
        localB_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_12_we0 = 1'b1;
    end else begin
        localB_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_13_ce0 = 1'b1;
    end else begin
        localB_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_13_we0 = 1'b1;
    end else begin
        localB_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_14_ce0 = 1'b1;
    end else begin
        localB_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_14_we0 = 1'b1;
    end else begin
        localB_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_15_ce0 = 1'b1;
    end else begin
        localB_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_15_we0 = 1'b1;
    end else begin
        localB_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_16_ce0 = 1'b1;
    end else begin
        localB_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_16_we0 = 1'b1;
    end else begin
        localB_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_17_ce0 = 1'b1;
    end else begin
        localB_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_17_we0 = 1'b1;
    end else begin
        localB_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_18_ce0 = 1'b1;
    end else begin
        localB_V_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_18_we0 = 1'b1;
    end else begin
        localB_V_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_19_ce0 = 1'b1;
    end else begin
        localB_V_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_19_we0 = 1'b1;
    end else begin
        localB_V_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_1_ce0 = 1'b1;
    end else begin
        localB_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_1_we0 = 1'b1;
    end else begin
        localB_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_20_ce0 = 1'b1;
    end else begin
        localB_V_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_20_we0 = 1'b1;
    end else begin
        localB_V_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_21_ce0 = 1'b1;
    end else begin
        localB_V_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_21_we0 = 1'b1;
    end else begin
        localB_V_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_22_ce0 = 1'b1;
    end else begin
        localB_V_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_22_we0 = 1'b1;
    end else begin
        localB_V_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_23_ce0 = 1'b1;
    end else begin
        localB_V_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_23_we0 = 1'b1;
    end else begin
        localB_V_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_24_ce0 = 1'b1;
    end else begin
        localB_V_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_24_we0 = 1'b1;
    end else begin
        localB_V_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_25_ce0 = 1'b1;
    end else begin
        localB_V_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_25_we0 = 1'b1;
    end else begin
        localB_V_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_26_ce0 = 1'b1;
    end else begin
        localB_V_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_26_we0 = 1'b1;
    end else begin
        localB_V_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_27_ce0 = 1'b1;
    end else begin
        localB_V_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd27) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_27_we0 = 1'b1;
    end else begin
        localB_V_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_28_ce0 = 1'b1;
    end else begin
        localB_V_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd28) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_28_we0 = 1'b1;
    end else begin
        localB_V_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_29_ce0 = 1'b1;
    end else begin
        localB_V_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd29) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_29_we0 = 1'b1;
    end else begin
        localB_V_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_2_ce0 = 1'b1;
    end else begin
        localB_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_2_we0 = 1'b1;
    end else begin
        localB_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_30_ce0 = 1'b1;
    end else begin
        localB_V_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd30) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_30_we0 = 1'b1;
    end else begin
        localB_V_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_31_ce0 = 1'b1;
    end else begin
        localB_V_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd31) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_31_we0 = 1'b1;
    end else begin
        localB_V_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_32_ce0 = 1'b1;
    end else begin
        localB_V_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd32) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_32_we0 = 1'b1;
    end else begin
        localB_V_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_33_ce0 = 1'b1;
    end else begin
        localB_V_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd33) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_33_we0 = 1'b1;
    end else begin
        localB_V_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_34_ce0 = 1'b1;
    end else begin
        localB_V_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd34) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_34_we0 = 1'b1;
    end else begin
        localB_V_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_35_ce0 = 1'b1;
    end else begin
        localB_V_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd35) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_35_we0 = 1'b1;
    end else begin
        localB_V_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_36_ce0 = 1'b1;
    end else begin
        localB_V_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd36) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_36_we0 = 1'b1;
    end else begin
        localB_V_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_37_ce0 = 1'b1;
    end else begin
        localB_V_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd37) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_37_we0 = 1'b1;
    end else begin
        localB_V_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_38_ce0 = 1'b1;
    end else begin
        localB_V_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd38) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_38_we0 = 1'b1;
    end else begin
        localB_V_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_39_ce0 = 1'b1;
    end else begin
        localB_V_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd39) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_39_we0 = 1'b1;
    end else begin
        localB_V_39_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_3_ce0 = 1'b1;
    end else begin
        localB_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_3_we0 = 1'b1;
    end else begin
        localB_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_40_ce0 = 1'b1;
    end else begin
        localB_V_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd40) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_40_we0 = 1'b1;
    end else begin
        localB_V_40_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_41_ce0 = 1'b1;
    end else begin
        localB_V_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd41) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_41_we0 = 1'b1;
    end else begin
        localB_V_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_42_ce0 = 1'b1;
    end else begin
        localB_V_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd42) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_42_we0 = 1'b1;
    end else begin
        localB_V_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_43_ce0 = 1'b1;
    end else begin
        localB_V_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd43) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_43_we0 = 1'b1;
    end else begin
        localB_V_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_44_ce0 = 1'b1;
    end else begin
        localB_V_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd44) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_44_we0 = 1'b1;
    end else begin
        localB_V_44_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_45_ce0 = 1'b1;
    end else begin
        localB_V_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd45) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_45_we0 = 1'b1;
    end else begin
        localB_V_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_46_ce0 = 1'b1;
    end else begin
        localB_V_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd46) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_46_we0 = 1'b1;
    end else begin
        localB_V_46_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_47_ce0 = 1'b1;
    end else begin
        localB_V_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd47) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_47_we0 = 1'b1;
    end else begin
        localB_V_47_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_48_ce0 = 1'b1;
    end else begin
        localB_V_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd48) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_48_we0 = 1'b1;
    end else begin
        localB_V_48_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_49_ce0 = 1'b1;
    end else begin
        localB_V_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd49) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_49_we0 = 1'b1;
    end else begin
        localB_V_49_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_4_ce0 = 1'b1;
    end else begin
        localB_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_4_we0 = 1'b1;
    end else begin
        localB_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_50_ce0 = 1'b1;
    end else begin
        localB_V_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd50) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_50_we0 = 1'b1;
    end else begin
        localB_V_50_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_51_ce0 = 1'b1;
    end else begin
        localB_V_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd51) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_51_we0 = 1'b1;
    end else begin
        localB_V_51_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_52_ce0 = 1'b1;
    end else begin
        localB_V_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd52) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_52_we0 = 1'b1;
    end else begin
        localB_V_52_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_53_ce0 = 1'b1;
    end else begin
        localB_V_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd53) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_53_we0 = 1'b1;
    end else begin
        localB_V_53_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_54_ce0 = 1'b1;
    end else begin
        localB_V_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd54) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_54_we0 = 1'b1;
    end else begin
        localB_V_54_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_55_ce0 = 1'b1;
    end else begin
        localB_V_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd55) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_55_we0 = 1'b1;
    end else begin
        localB_V_55_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_56_ce0 = 1'b1;
    end else begin
        localB_V_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd56) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_56_we0 = 1'b1;
    end else begin
        localB_V_56_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_57_ce0 = 1'b1;
    end else begin
        localB_V_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd57) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_57_we0 = 1'b1;
    end else begin
        localB_V_57_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_58_ce0 = 1'b1;
    end else begin
        localB_V_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd58) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_58_we0 = 1'b1;
    end else begin
        localB_V_58_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_59_ce0 = 1'b1;
    end else begin
        localB_V_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd59) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_59_we0 = 1'b1;
    end else begin
        localB_V_59_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_5_ce0 = 1'b1;
    end else begin
        localB_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_5_we0 = 1'b1;
    end else begin
        localB_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_60_ce0 = 1'b1;
    end else begin
        localB_V_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd60) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_60_we0 = 1'b1;
    end else begin
        localB_V_60_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_61_ce0 = 1'b1;
    end else begin
        localB_V_61_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd61) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_61_we0 = 1'b1;
    end else begin
        localB_V_61_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_62_ce0 = 1'b1;
    end else begin
        localB_V_62_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd62) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_62_we0 = 1'b1;
    end else begin
        localB_V_62_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_63_ce0 = 1'b1;
    end else begin
        localB_V_63_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd63) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_63_we0 = 1'b1;
    end else begin
        localB_V_63_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_6_ce0 = 1'b1;
    end else begin
        localB_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_6_we0 = 1'b1;
    end else begin
        localB_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_7_ce0 = 1'b1;
    end else begin
        localB_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_7_we0 = 1'b1;
    end else begin
        localB_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_8_ce0 = 1'b1;
    end else begin
        localB_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_8_we0 = 1'b1;
    end else begin
        localB_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_9_ce0 = 1'b1;
    end else begin
        localB_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_9_we0 = 1'b1;
    end else begin
        localB_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_ce0 = 1'b1;
    end else begin
        localB_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln34_reg_1434 == 6'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        localB_V_we0 = 1'b1;
    end else begin
        localB_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_mem_Addr_A = B_mem_Addr_A_orig << 32'd0;

assign B_mem_Addr_A_orig = zext_ln34_fu_1303_p1;

assign B_mem_Din_A = 8'd0;

assign B_mem_WEN_A = 1'd0;

assign add_ln18_fu_1297_p2 = (zext_ln32_fu_1293_p1 + p_mid_fu_1285_p3);

assign add_ln31_1_fu_1267_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign add_ln31_fu_1241_p2 = (ap_sig_allocacmp_indvar_flatten138_load + 13'd1);

assign add_ln32_fu_1312_p2 = (select_ln31_fu_1259_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln31_fu_1235_p2 = ((ap_sig_allocacmp_indvar_flatten138_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_1253_p2 = ((ap_sig_allocacmp_j_load == 7'd64) ? 1'b1 : 1'b0);

assign localB_V_10_address0 = zext_ln31_fu_1333_p1;

assign localB_V_10_d0 = B_mem_Dout_A;

assign localB_V_11_address0 = zext_ln31_fu_1333_p1;

assign localB_V_11_d0 = B_mem_Dout_A;

assign localB_V_12_address0 = zext_ln31_fu_1333_p1;

assign localB_V_12_d0 = B_mem_Dout_A;

assign localB_V_13_address0 = zext_ln31_fu_1333_p1;

assign localB_V_13_d0 = B_mem_Dout_A;

assign localB_V_14_address0 = zext_ln31_fu_1333_p1;

assign localB_V_14_d0 = B_mem_Dout_A;

assign localB_V_15_address0 = zext_ln31_fu_1333_p1;

assign localB_V_15_d0 = B_mem_Dout_A;

assign localB_V_16_address0 = zext_ln31_fu_1333_p1;

assign localB_V_16_d0 = B_mem_Dout_A;

assign localB_V_17_address0 = zext_ln31_fu_1333_p1;

assign localB_V_17_d0 = B_mem_Dout_A;

assign localB_V_18_address0 = zext_ln31_fu_1333_p1;

assign localB_V_18_d0 = B_mem_Dout_A;

assign localB_V_19_address0 = zext_ln31_fu_1333_p1;

assign localB_V_19_d0 = B_mem_Dout_A;

assign localB_V_1_address0 = zext_ln31_fu_1333_p1;

assign localB_V_1_d0 = B_mem_Dout_A;

assign localB_V_20_address0 = zext_ln31_fu_1333_p1;

assign localB_V_20_d0 = B_mem_Dout_A;

assign localB_V_21_address0 = zext_ln31_fu_1333_p1;

assign localB_V_21_d0 = B_mem_Dout_A;

assign localB_V_22_address0 = zext_ln31_fu_1333_p1;

assign localB_V_22_d0 = B_mem_Dout_A;

assign localB_V_23_address0 = zext_ln31_fu_1333_p1;

assign localB_V_23_d0 = B_mem_Dout_A;

assign localB_V_24_address0 = zext_ln31_fu_1333_p1;

assign localB_V_24_d0 = B_mem_Dout_A;

assign localB_V_25_address0 = zext_ln31_fu_1333_p1;

assign localB_V_25_d0 = B_mem_Dout_A;

assign localB_V_26_address0 = zext_ln31_fu_1333_p1;

assign localB_V_26_d0 = B_mem_Dout_A;

assign localB_V_27_address0 = zext_ln31_fu_1333_p1;

assign localB_V_27_d0 = B_mem_Dout_A;

assign localB_V_28_address0 = zext_ln31_fu_1333_p1;

assign localB_V_28_d0 = B_mem_Dout_A;

assign localB_V_29_address0 = zext_ln31_fu_1333_p1;

assign localB_V_29_d0 = B_mem_Dout_A;

assign localB_V_2_address0 = zext_ln31_fu_1333_p1;

assign localB_V_2_d0 = B_mem_Dout_A;

assign localB_V_30_address0 = zext_ln31_fu_1333_p1;

assign localB_V_30_d0 = B_mem_Dout_A;

assign localB_V_31_address0 = zext_ln31_fu_1333_p1;

assign localB_V_31_d0 = B_mem_Dout_A;

assign localB_V_32_address0 = zext_ln31_fu_1333_p1;

assign localB_V_32_d0 = B_mem_Dout_A;

assign localB_V_33_address0 = zext_ln31_fu_1333_p1;

assign localB_V_33_d0 = B_mem_Dout_A;

assign localB_V_34_address0 = zext_ln31_fu_1333_p1;

assign localB_V_34_d0 = B_mem_Dout_A;

assign localB_V_35_address0 = zext_ln31_fu_1333_p1;

assign localB_V_35_d0 = B_mem_Dout_A;

assign localB_V_36_address0 = zext_ln31_fu_1333_p1;

assign localB_V_36_d0 = B_mem_Dout_A;

assign localB_V_37_address0 = zext_ln31_fu_1333_p1;

assign localB_V_37_d0 = B_mem_Dout_A;

assign localB_V_38_address0 = zext_ln31_fu_1333_p1;

assign localB_V_38_d0 = B_mem_Dout_A;

assign localB_V_39_address0 = zext_ln31_fu_1333_p1;

assign localB_V_39_d0 = B_mem_Dout_A;

assign localB_V_3_address0 = zext_ln31_fu_1333_p1;

assign localB_V_3_d0 = B_mem_Dout_A;

assign localB_V_40_address0 = zext_ln31_fu_1333_p1;

assign localB_V_40_d0 = B_mem_Dout_A;

assign localB_V_41_address0 = zext_ln31_fu_1333_p1;

assign localB_V_41_d0 = B_mem_Dout_A;

assign localB_V_42_address0 = zext_ln31_fu_1333_p1;

assign localB_V_42_d0 = B_mem_Dout_A;

assign localB_V_43_address0 = zext_ln31_fu_1333_p1;

assign localB_V_43_d0 = B_mem_Dout_A;

assign localB_V_44_address0 = zext_ln31_fu_1333_p1;

assign localB_V_44_d0 = B_mem_Dout_A;

assign localB_V_45_address0 = zext_ln31_fu_1333_p1;

assign localB_V_45_d0 = B_mem_Dout_A;

assign localB_V_46_address0 = zext_ln31_fu_1333_p1;

assign localB_V_46_d0 = B_mem_Dout_A;

assign localB_V_47_address0 = zext_ln31_fu_1333_p1;

assign localB_V_47_d0 = B_mem_Dout_A;

assign localB_V_48_address0 = zext_ln31_fu_1333_p1;

assign localB_V_48_d0 = B_mem_Dout_A;

assign localB_V_49_address0 = zext_ln31_fu_1333_p1;

assign localB_V_49_d0 = B_mem_Dout_A;

assign localB_V_4_address0 = zext_ln31_fu_1333_p1;

assign localB_V_4_d0 = B_mem_Dout_A;

assign localB_V_50_address0 = zext_ln31_fu_1333_p1;

assign localB_V_50_d0 = B_mem_Dout_A;

assign localB_V_51_address0 = zext_ln31_fu_1333_p1;

assign localB_V_51_d0 = B_mem_Dout_A;

assign localB_V_52_address0 = zext_ln31_fu_1333_p1;

assign localB_V_52_d0 = B_mem_Dout_A;

assign localB_V_53_address0 = zext_ln31_fu_1333_p1;

assign localB_V_53_d0 = B_mem_Dout_A;

assign localB_V_54_address0 = zext_ln31_fu_1333_p1;

assign localB_V_54_d0 = B_mem_Dout_A;

assign localB_V_55_address0 = zext_ln31_fu_1333_p1;

assign localB_V_55_d0 = B_mem_Dout_A;

assign localB_V_56_address0 = zext_ln31_fu_1333_p1;

assign localB_V_56_d0 = B_mem_Dout_A;

assign localB_V_57_address0 = zext_ln31_fu_1333_p1;

assign localB_V_57_d0 = B_mem_Dout_A;

assign localB_V_58_address0 = zext_ln31_fu_1333_p1;

assign localB_V_58_d0 = B_mem_Dout_A;

assign localB_V_59_address0 = zext_ln31_fu_1333_p1;

assign localB_V_59_d0 = B_mem_Dout_A;

assign localB_V_5_address0 = zext_ln31_fu_1333_p1;

assign localB_V_5_d0 = B_mem_Dout_A;

assign localB_V_60_address0 = zext_ln31_fu_1333_p1;

assign localB_V_60_d0 = B_mem_Dout_A;

assign localB_V_61_address0 = zext_ln31_fu_1333_p1;

assign localB_V_61_d0 = B_mem_Dout_A;

assign localB_V_62_address0 = zext_ln31_fu_1333_p1;

assign localB_V_62_d0 = B_mem_Dout_A;

assign localB_V_63_address0 = zext_ln31_fu_1333_p1;

assign localB_V_63_d0 = B_mem_Dout_A;

assign localB_V_6_address0 = zext_ln31_fu_1333_p1;

assign localB_V_6_d0 = B_mem_Dout_A;

assign localB_V_7_address0 = zext_ln31_fu_1333_p1;

assign localB_V_7_d0 = B_mem_Dout_A;

assign localB_V_8_address0 = zext_ln31_fu_1333_p1;

assign localB_V_8_d0 = B_mem_Dout_A;

assign localB_V_9_address0 = zext_ln31_fu_1333_p1;

assign localB_V_9_d0 = B_mem_Dout_A;

assign localB_V_address0 = zext_ln31_fu_1333_p1;

assign localB_V_d0 = B_mem_Dout_A;

assign p_mid_fu_1285_p3 = {{trunc_ln31_fu_1281_p1}, {6'd0}};

assign select_ln31_1_fu_1273_p3 = ((icmp_ln32_fu_1253_p2[0:0] == 1'b1) ? add_ln31_1_fu_1267_p2 : ap_sig_allocacmp_i_load);

assign select_ln31_fu_1259_p3 = ((icmp_ln32_fu_1253_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_load);

assign trunc_ln31_fu_1281_p1 = select_ln31_1_fu_1273_p3[5:0];

assign trunc_ln34_fu_1308_p1 = select_ln31_fu_1259_p3[5:0];

assign zext_ln31_fu_1333_p1 = select_ln31_1_reg_1424;

assign zext_ln32_fu_1293_p1 = select_ln31_fu_1259_p3;

assign zext_ln34_fu_1303_p1 = add_ln18_fu_1297_p2;

endmodule //systolic_4x4_systolic_4x4_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4
